<?php
declare(strict_types=1);

namespace NHK\Core\Application\Governance;

use NHK\Core\Domain\Capture\CaptureRecord;

/** Admission for the required Article subject edge generated by Editorial Capture. */
final class CaptureChildRelationStagingAdmission
{
    /** @param array<string,mixed> $scope @param array<string,mixed> $input @param list<array<string,mixed>> $assets */
    public function __invoke(bool $admitted, array $scope, CaptureRecord $capture, array $input, array $assets): bool
    {
        if ($admitted) return true;
        if (($scope['approved'] ?? false) !== true
            || ($scope['environment'] ?? '') !== 'staging'
            || ($scope['operation_family'] ?? '') !== 'capture_child_relation'
            || ($scope['entity_type'] ?? '') !== 'relation'
            || ($scope['operation'] ?? '') !== 'relation_create'
            || ($scope['writer'] ?? '') !== 'canonical_governed'
            || ($scope['entrypoint'] ?? '') !== 'nhk.capture.ingest'
            || ($scope['capture_id'] ?? '') !== $capture->captureId
            || ($scope['capture_fingerprint'] ?? '') !== $capture->requestFingerprint
            || ($scope['owner_type'] ?? '') !== 'article'
            || ($scope['source_type'] ?? '') !== 'wp_post'
            || ($scope['source_id'] ?? '') === ''
            || ($scope['predicate'] ?? '') !== 'about'
            || ($scope['target_type'] ?? '') === ''
            || ($scope['target_id'] ?? '') === ''
            || !preg_match('/^[a-f0-9]{64}$/i', (string) ($scope['payload_fingerprint'] ?? ''))
            || !preg_match('/^[a-f0-9]{64}$/i', (string) ($scope['proposal_command_fingerprint'] ?? ''))) return false;
        $articleId = (int) ($capture->articleId ?? 0);
        $expectedSource = (function_exists('get_current_blog_id') ? (int) get_current_blog_id() : 1) . ':' . $articleId;
        return $articleId > 0 && ($scope['owner_id'] ?? '') === (string) $articleId && ($scope['source_id'] ?? '') === $expectedSource;
    }
}
