<?php
declare(strict_types=1);
namespace NHK\Tests\Unit;
use NHK\Core\Application\Authority\AuthorityService;
use NHK\Core\Authority\Exception\{AuthorityAlreadyActive,AuthorityAlreadyRetired,AuthorityRevisionConflict,InvalidPayload,StableKeyCollision,StableKeyMismatch};
use NHK\Core\Domain\Authority\{AuthorityEntity,CanonicalEntityTypeCatalog,EntityTypeDefinition,EntityTypeRegistry};
use NHK\Core\Infrastructure\Graph\AuthorityEndpointResolver;
use NHK\Core\Domain\Graph\NodeReference;
use NHK\Tests\Support\InMemoryAuthorityRepository;
use PHPUnit\Framework\TestCase;
final class AuthorityCoreTest extends TestCase {
 private function service(?InMemoryAuthorityRepository $r=null):array{$r??=new InMemoryAuthorityRepository();$types=new EntityTypeRegistry();$types->register(new EntityTypeDefinition('brand',1,true,[]));return [new AuthorityService($r,$types),$r,$types];}
 public function test_brand_create_uses_uuid_and_stable_key_is_idempotent():void{[$s]=$this->service();$a=$s->create('brand','odo','Odo');$b=$s->create('brand','odo','Odo');$this->assertSame($a->canonicalId,$b->canonicalId);$this->assertSame(1,$a->revision);$this->assertSame('brand',$a->entityType);}
 public function test_authority_entity_rejects_malformed_canonical_uuid():void{$this->expectException(\NHK\Core\Graph\Exception\InvalidEndpointReference::class);new AuthorityEntity('not-a-uuid','brand','invalid-uuid','Invalid UUID',1,[]);}
 public function test_uuid_codec_distinguishes_canonical_and_malformed_public_ids():void{self::assertTrue(\NHK\Core\Shared\Uuid\UuidCodec::isValid(\NHK\Core\Shared\Uuid\UuidCodec::newV7()));self::assertFalse(\NHK\Core\Shared\Uuid\UuidCodec::isValid('00000000-0000-0000-0000-000000000000'));self::assertFalse(\NHK\Core\Shared\Uuid\UuidCodec::isValid('not-a-uuid'));}
 public function test_unknown_payload_and_collision_are_rejected():void{[$s]=$this->service();$s->create('brand','a','A');$this->expectException(StableKeyCollision::class);$s->create('brand','a','Other');}
 public function test_payload_fields_are_validated():void{[$s]=$this->service();$this->expectException(InvalidPayload::class);$s->create('brand','a','A',['unknown'=>1]);}
 public function test_lifecycle_preserves_uuid_and_revision_locking():void{[$s]=$this->service();$a=$s->create('brand','a','A');$r=$s->rename($a->canonicalId,'B',1);$this->assertSame(2,$r->revision);$ret=$s->retire($r->canonicalId,2);$this->assertFalse($ret->active());$live=$s->reactivate($ret->canonicalId,3);$this->assertTrue($live->active());$this->assertSame($a->canonicalId,$live->canonicalId);$this->expectException(AuthorityRevisionConflict::class);$s->rename($live->canonicalId,'C',1);}
 public function test_generic_resolver_validates_uuid_and_retired_entities_remain_graph_endpoints():void{[$s,$r,$types]=$this->service();$a=$s->create('brand','a','A');$resolver=new AuthorityEndpointResolver($types,$r);$ref=$resolver->normalize(new NodeReference('brand',$a->canonicalId));$this->assertTrue($resolver->exists($ref));$s->retire($a->canonicalId,1);$this->assertTrue($resolver->exists($ref));$this->expectException(\NHK\Core\Graph\Exception\InvalidEndpointReference::class);$resolver->normalize(new NodeReference('brand','00000000-0000-0000-0000-000000000000'));}
 public function test_already_retired_is_typed_error():void{[$s]=$this->service();$a=$s->create('brand','retired','Retired');$retired=$s->retire($a->canonicalId,1);$this->expectException(AuthorityAlreadyRetired::class);$s->retire($retired->canonicalId,2);}
 public function test_already_active_is_typed_error():void{[$s]=$this->service();$a=$s->create('brand','active','Active');$this->expectException(AuthorityAlreadyActive::class);$s->reactivate($a->canonicalId,1);}
 public function test_canonical_catalog_registers_all_target_types_with_explicit_schema_contracts():void{$registry=new EntityTypeRegistry();CanonicalEntityTypeCatalog::registerInto($registry);self::assertSame(['brand','model','variant','movement','music','component','classification','specimen','product'],array_map(static fn(EntityTypeDefinition $d):string=>$d->type,$registry->all()));foreach($registry->all() as $definition){self::assertTrue($definition->graphEnabled);self::assertSame($definition->allowedFields,array_keys($definition->fieldTypes));}}
 public function test_registry_rejects_conflicting_duplicate_and_invalid_schema_definitions():void{$registry=new EntityTypeRegistry();$definition=new EntityTypeDefinition('brand',1,true,['description'],[],['description'=>'string']);$registry->register($definition);$registry->register($definition);$this->expectException(\InvalidArgumentException::class);$registry->register(new EntityTypeDefinition('brand',2,true,['description'],[],['description'=>'string']));}
 public function test_canonical_payload_field_types_are_validated():void{$registry=new EntityTypeRegistry();CanonicalEntityTypeCatalog::registerInto($registry);$service=new AuthorityService(new InMemoryAuthorityRepository(),$registry);$this->expectException(InvalidPayload::class);$service->create('movement','caliber-1','Caliber',['frequency_hz'=>'wrong']);}
 public function test_type_specific_relation_uuid_and_url_formats_are_fail_closed():void{$registry=new EntityTypeRegistry();CanonicalEntityTypeCatalog::registerInto($registry);$service=new AuthorityService(new InMemoryAuthorityRepository(),$registry);$this->expectException(InvalidPayload::class);$service->create('model','model-invalid','Model',['brand_uuid'=>'00000000-0000-0000-0000-000000000000']);}
 public function test_type_specific_product_url_rejects_non_http_reference():void{$registry=new EntityTypeRegistry();CanonicalEntityTypeCatalog::registerInto($registry);$service=new AuthorityService(new InMemoryAuthorityRepository(),$registry);$this->expectException(InvalidPayload::class);$service->create('product','product-invalid','Product',['url'=>'javascript:alert(1)']);}
 public function test_type_specific_url_format_accepts_https_product_reference():void{$registry=new EntityTypeRegistry();CanonicalEntityTypeCatalog::registerInto($registry);$service=new AuthorityService(new InMemoryAuthorityRepository(),$registry);$entity=$service->create('product','product-valid','Product',['url'=>'https://example.com/listing/1']);self::assertSame('https://example.com/listing/1',$entity->payload['url']);}
 public function test_payload_update_preserves_identity_and_uses_revision_locking():void{$registry=new EntityTypeRegistry();CanonicalEntityTypeCatalog::registerInto($registry);$service=new AuthorityService(new InMemoryAuthorityRepository(),$registry);$entity=$service->create('model','model-1','Model');$updated=$service->update($entity->canonicalId,['launch_year'=>1970],1);self::assertSame($entity->canonicalId,$updated->canonicalId);self::assertSame(2,$updated->revision);self::assertSame(['launch_year'=>1970],$updated->payload);$this->expectException(AuthorityRevisionConflict::class);$service->update($entity->canonicalId,['launch_year'=>1971],1);}
 public function test_stable_key_rekey_preserves_uuid_payload_name_and_state_and_increments_revision_once():void{[$service,$repository]=$this->service();$entity=$service->create('brand','odo','Odo');$rekeyed=$service->rekey($entity->canonicalId,'odo','nhk:brand:odo',1);self::assertSame($entity->canonicalId,$rekeyed->canonicalId);self::assertSame('nhk:brand:odo',$rekeyed->stableKey);self::assertSame('Odo',$rekeyed->canonicalName);self::assertSame([],$rekeyed->payload);self::assertTrue($rekeyed->active());self::assertSame(2,$rekeyed->revision);self::assertNull($repository->findByStableKey('brand','odo'));self::assertSame($entity->canonicalId,$repository->findByStableKey('brand','nhk:brand:odo')?->canonicalId);}
 public function test_rekey_fails_closed_on_exact_old_key_mismatch():void{[$service]=$this->service();$entity=$service->create('brand','odo','Odo');$this->expectException(StableKeyMismatch::class);$service->rekey($entity->canonicalId,'wrong-old-key','nhk:brand:odo',1);}
 public function test_rekey_fails_closed_on_target_collision():void{[$service]=$this->service();$entity=$service->create('brand','odo','Odo');$service->create('brand','nhk:brand:odo','Odo New');$this->expectException(StableKeyCollision::class);$service->rekey($entity->canonicalId,'odo','nhk:brand:odo',1);}
 public function test_rekey_uses_revision_locking():void{[$service]=$this->service();$entity=$service->create('brand','odo','Odo');$service->rekey($entity->canonicalId,'odo','odo-new',1);$this->expectException(AuthorityRevisionConflict::class);$service->rekey($entity->canonicalId,'odo-new','odo-final',1);}
 public function test_rekey_audit_retains_old_and_new_stable_keys():void{$events=[];$types=new EntityTypeRegistry();$types->register(new EntityTypeDefinition('brand',1,true,[]));$service=new AuthorityService(new InMemoryAuthorityRepository(),$types,new class($events) implements \NHK\Core\Contracts\Authority\AuthorityAuditSink{public function __construct(private array &$events){} public function record(string $event, AuthorityEntity $entity, array $context=[]):void{$this->events[]=['event'=>$event,'entity'=>$entity,'context'=>$context];}});$entity=$service->create('brand','odo','Odo');$service->rekey($entity->canonicalId,'odo','nhk:brand:odo',1);self::assertSame('rekeyed',$events[1]['event']);self::assertSame('odo',$events[1]['context']['old_stable_key']);self::assertSame('nhk:brand:odo',$events[1]['context']['new_stable_key']);self::assertSame($entity->canonicalId,$events[1]['entity']->canonicalId);}
}
