<?php
declare(strict_types=1);
namespace NHK\Tests\Support;
use NHK\Core\Contracts\Graph\GraphRepository;
use NHK\Core\Domain\Graph\{EdgeState,GraphEdge,GraphNode,NodeReference,PredicateDefinition};
use NHK\Core\Graph\Exception\{GraphNodeInUse,RelationAlreadyActive,RelationAlreadyRetired,RelationCardinalityViolation,RelationRevisionConflict};
use NHK\Core\Shared\Uuid\UuidCodec;
final class InMemoryGraphRepository implements GraphRepository {
    private array $nodes=[]; private array $edges=[]; private int $nextNode=1;
    public function resolveNode(NodeReference $reference): GraphNode { return $this->nodes[$reference->key()] ??= new GraphNode($this->nextNode++, $reference); }
    public function findNode(NodeReference $reference): ?GraphNode { return $this->nodes[$reference->key()] ?? null; }
    public function createEdge(GraphNode $source,PredicateDefinition $predicate,GraphNode $target): GraphEdge { $key=$source->internal_node_id.'|'.$predicate->key.'|'.$target->internal_node_id; if(isset($this->edges[$key])) { if(!$this->edges[$key]->isActive()) throw new RelationAlreadyRetired('Retired relation requires explicit reactivation.'); return $this->edges[$key]; } foreach($this->edges as $edge) if($edge->isActive() && $edge->predicate===$predicate->key && (($predicate->outbound_cardinality==='ONE'&&$edge->source->internal_node_id===$source->internal_node_id)||($predicate->inbound_cardinality==='ONE'&&$edge->target->internal_node_id===$target->internal_node_id))) throw new RelationCardinalityViolation('Cardinality violated.'); $edge=new GraphEdge(UuidCodec::newV7(),$source,$predicate->key,$target); return $this->edges[$key]=$edge; }
    public function findEdge(NodeReference $source,string $predicate,NodeReference $target): ?GraphEdge { $s=$this->findNode($source);$t=$this->findNode($target); if(!$s||!$t)return null; return $this->edges[$s->internal_node_id.'|'.$predicate.'|'.$t->internal_node_id]??null; }
    public function findByUuid(string $uuid): ?GraphEdge { foreach($this->edges as $edge)if($edge->edge_uuid===$uuid)return $edge;return null; }
    public function outgoing(GraphNode $source,?string $predicate,int $after_id,int $limit,bool $include_retired,?string $target_type=null): array { return $this->listed($source,true,$predicate,$include_retired,$limit,$after_id,$target_type); }
    public function incoming(GraphNode $target,?string $predicate,int $after_id,int $limit,bool $include_retired,?string $source_type=null): array { return $this->listed($target,false,$predicate,$include_retired,$limit,$after_id,$source_type); }
    public function retire(GraphEdge $edge,int $expected_revision): GraphEdge { return $this->transition($edge,$expected_revision,EdgeState::RETIRED); }
    public function reactivate(GraphEdge $edge,int $expected_revision): GraphEdge { return $this->transition($edge,$expected_revision,EdgeState::ACTIVE); }
    public function nodeHasEdges(GraphNode $node): bool { foreach($this->edges as $edge)if($edge->source->internal_node_id===$node->internal_node_id||$edge->target->internal_node_id===$node->internal_node_id)return true;return false; }
    public function deleteNode(GraphNode $node): void { if($this->nodeHasEdges($node))throw new GraphNodeInUse("Graph node still has edges."); unset($this->nodes[$node->reference->key()]); }
    private function transition(GraphEdge $edge,int $expected,EdgeState $state): GraphEdge { if($edge->revision!==$expected)throw new RelationRevisionConflict('Graph edge revision conflict.'); if($edge->state===$state)throw $state===EdgeState::ACTIVE?new RelationAlreadyActive('Relation is already active.'):new RelationAlreadyRetired('Relation is already retired.'); $new=new GraphEdge($edge->edge_uuid,$edge->source,$edge->predicate,$edge->target,$state,$expected+1,$edge->created_at,'now',$state===EdgeState::RETIRED?'now':null); foreach($this->edges as $key=>$candidate)if($candidate->edge_uuid===$edge->edge_uuid)$this->edges[$key]=$new;return $new; }
    private function listed(GraphNode $node,bool $out,?string $predicate,bool $include,int $limit,int $after=0,?string $otherType=null): array { $items=[];$ids=[];$id=0;foreach($this->edges as $edge){++$id;if($id<=$after)continue;$other=$out?$edge->target:$edge->source;if(($out?$edge->source:$edge->target)->internal_node_id===$node->internal_node_id&&($predicate===null||$edge->predicate===$predicate)&&($otherType===null||$other->reference->endpoint_type===$otherType)&&($include||$edge->isActive())){$items[]=$edge;$ids[]=$id;}}$next=count($items)>$limit?$ids[$limit-1]:null;return ["items"=>array_slice($items,0,$limit),"next_cursor"=>$next]; }
}
