<?php
declare(strict_types=1);

namespace NHK\Core\Infrastructure\Article;

use NHK\Core\Contracts\Article\OwnerPublicationDecisionRepository;
use NHK\Core\Domain\Article\{ArticlePublicationOutcome, OwnerPublicationDecision};

final class WpdbOwnerPublicationDecisionRepository implements OwnerPublicationDecisionRepository
{
    public function __construct(private ?object $database = null) {}
    private function db(): object { global $wpdb; return $this->database ?? $wpdb; }
    private function table(): string { return $this->db()->prefix . 'nhk_owner_publication_decisions'; }
    public function findByIdempotencyKey(string $key): ?OwnerPublicationDecision { $row = $this->db()->get_row($this->db()->prepare('SELECT * FROM ' . $this->table() . ' WHERE idempotency_key=%s ORDER BY id DESC LIMIT 1', $key), defined('ARRAY_A') ? ARRAY_A : 1); return is_array($row) ? $this->hydrate($row) : null; }
    public function findActiveApproval(int $postId, string $token, string $policyVersion, string $blockerFingerprint, string $principalId): ?OwnerPublicationDecision { $row = $this->db()->get_row($this->db()->prepare('SELECT * FROM ' . $this->table() . ' WHERE wp_post_id=%d AND editorial_state_token=%s AND policy_version=%s AND blocker_fingerprint=%s AND principal_id=%s AND decision=%s ORDER BY id DESC LIMIT 1', $postId, $token, $policyVersion, $blockerFingerprint, $principalId, 'APPROVED_WITH_EXCEPTIONS'), defined('ARRAY_A') ? ARRAY_A : 1); return is_array($row) ? $this->hydrate($row) : null; }
    public function create(OwnerPublicationDecision $decision): OwnerPublicationDecision { $existing = $this->findByIdempotencyKey($decision->idempotencyKey); if ($existing !== null) { if (!hash_equals($existing->requestFingerprint, $decision->requestFingerprint)) throw new \RuntimeException('OWNER_PUBLICATION_IDEMPOTENCY_CONFLICT'); return $existing; } return $this->insert($decision); }
    public function append(OwnerPublicationDecision $decision): OwnerPublicationDecision { return $this->insert($decision); }
    private function insert(OwnerPublicationDecision $d): OwnerPublicationDecision { $db = $this->db(); $ok = $db->query($db->prepare('INSERT INTO ' . $this->table() . ' (decision_id,idempotency_key,request_fingerprint,wp_post_id,decision,gate_outcome,diagnostics_json,overridden_codes_json,blocker_fingerprint,editorial_state_token,policy_version,principal_id,approval_provenance_json,approved_at,expires_at,stage,publish_attempt_json,readback_json,final_outcome,revision) VALUES (%s,%s,%s,%d,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%d)', $d->decisionId, $d->idempotencyKey, $d->requestFingerprint, $d->wpPostId, $d->decision, $d->gateOutcome->value, wp_json_encode($d->diagnostics), wp_json_encode($d->overriddenDiagnosticCodes), $d->blockerFingerprint, $d->editorialStateToken, $d->policyVersion, $d->principalId, wp_json_encode($d->approvalProvenance), $d->approvedAt, $d->expiresAt, $d->stage, wp_json_encode($d->publishAttempt), wp_json_encode($d->readback), $d->finalOutcome, $d->revision)); if ($ok === false) throw new \RuntimeException('OWNER_PUBLICATION_DECISION_INSERT_FAILED'); return $d; }
    private function hydrate(array $row): ?OwnerPublicationDecision { try { return new OwnerPublicationDecision((string) $row['decision_id'], (string) $row['idempotency_key'], (string) $row['request_fingerprint'], (int) $row['wp_post_id'], (string) $row['decision'], ArticlePublicationOutcome::from((string) $row['gate_outcome']), (array) json_decode((string) $row['diagnostics_json'], true, 512, JSON_THROW_ON_ERROR), (array) json_decode((string) $row['overridden_codes_json'], true, 512, JSON_THROW_ON_ERROR), (string) $row['blocker_fingerprint'], (string) $row['editorial_state_token'], (string) $row['policy_version'], (string) $row['principal_id'], (array) json_decode((string) $row['approval_provenance_json'], true, 512, JSON_THROW_ON_ERROR), (string) $row['approved_at'], (string) $row['expires_at'], (string) $row['stage'], (array) json_decode((string) $row['publish_attempt_json'], true, 512, JSON_THROW_ON_ERROR), (array) json_decode((string) $row['readback_json'], true, 512, JSON_THROW_ON_ERROR), (string) $row['final_outcome'], (int) $row['revision']); } catch (\Throwable) { return null; } }
}
