<?php
declare(strict_types=1);
namespace NHK\Core\Infrastructure\Graph;
use NHK\Core\Contracts\Graph\GraphRelationContextRepository;
use NHK\Core\Domain\Graph\GraphRelationContext;
use NHK\Core\Shared\Uuid\UuidCodec;
final class WpdbGraphRelationContextRepository implements GraphRelationContextRepository
{
    private string $table;
    public function __construct(private object $database) { $this->table=$database->prefix.'nhk_graph_relation_context'; }
    public function create(GraphRelationContext $context):GraphRelationContext { $existing=$this->findByIdempotencyKey($context->idempotencyKey); if($existing){if($this->fingerprint($existing)===$this->fingerprint($context))return $existing;throw new \RuntimeException('GRAPH_RELATION_CONTEXT_IDEMPOTENCY_CONFLICT');} $now=gmdate('Y-m-d H:i:s.u'); $ok=$this->database->query($this->database->prepare("INSERT INTO {$this->table} (context_uuid,edge_uuid,source_revision,target_revision,scope_code,scope_subject_type,scope_subject_id,provenance_class,evidence_refs_json,approval_fingerprint,idempotency_key,state,revision,created_at,updated_at) VALUES (%s,%s,%d,%d,%s,%s,%s,%s,%s,%s,%s,%d,%d,%s,%s)",UuidCodec::toBinary($context->contextUuid),UuidCodec::toBinary($context->edgeUuid),$context->sourceRevision,$context->targetRevision,$context->scopeCode,$context->scopeSubjectType,$context->scopeSubjectId,$context->provenanceClass,wp_json_encode($context->evidenceRefs),$context->approvalFingerprint,$context->idempotencyKey,1,1,$now,$now)); if($ok===false)throw new \RuntimeException('GRAPH_RELATION_CONTEXT_CREATE_FAILED'); return $this->findByContextUuid($context->contextUuid)??$context; }
    public function findByContextUuid(string $uuid):?GraphRelationContext{return $this->hydrate($this->database->get_row($this->database->prepare("SELECT * FROM {$this->table} WHERE context_uuid=%s LIMIT 1",UuidCodec::toBinary($uuid)),ARRAY_A));}
    public function findByEdgeUuid(string $uuid):?GraphRelationContext{return $this->hydrate($this->database->get_row($this->database->prepare("SELECT * FROM {$this->table} WHERE edge_uuid=%s LIMIT 1",UuidCodec::toBinary($uuid)),ARRAY_A));}
    public function findByIdempotencyKey(string $key):?GraphRelationContext{return $this->hydrate($this->database->get_row($this->database->prepare("SELECT * FROM {$this->table} WHERE idempotency_key=%s LIMIT 1",$key),ARRAY_A));}
    public function update(GraphRelationContext $context,int $expectedRevision):GraphRelationContext{$ok=$this->database->query($this->database->prepare("UPDATE {$this->table} SET source_revision=%d,target_revision=%d,scope_code=%s,scope_subject_type=%s,scope_subject_id=%s,provenance_class=%s,evidence_refs_json=%s,approval_fingerprint=%s,revision=revision+1,updated_at=%s WHERE context_uuid=%s AND revision=%d",$context->sourceRevision,$context->targetRevision,$context->scopeCode,$context->scopeSubjectType,$context->scopeSubjectId,$context->provenanceClass,wp_json_encode($context->evidenceRefs),$context->approvalFingerprint,gmdate('Y-m-d H:i:s.u'),UuidCodec::toBinary($context->contextUuid),$expectedRevision));if($ok!==1)throw new \RuntimeException('GRAPH_RELATION_CONTEXT_REVISION_CONFLICT');return $this->findByContextUuid($context->contextUuid)??$context;}
    public function retire(GraphRelationContext $context,int $expectedRevision):GraphRelationContext{return $this->lifecycle($context,$expectedRevision,0,gmdate('Y-m-d H:i:s.u'));}
    public function reactivate(GraphRelationContext $context,int $expectedRevision):GraphRelationContext{return $this->lifecycle($context,$expectedRevision,1,null);}
    private function lifecycle(GraphRelationContext $c,int $expected,int $state,?string $retired):GraphRelationContext{$ok=$this->database->query($this->database->prepare("UPDATE {$this->table} SET state=%d,revision=revision+1,updated_at=%s,retired_at=%s WHERE context_uuid=%s AND revision=%d",$state,gmdate('Y-m-d H:i:s.u'),$retired,UuidCodec::toBinary($c->contextUuid),$expected));if($ok!==1)throw new \RuntimeException('GRAPH_RELATION_CONTEXT_REVISION_CONFLICT');return $this->findByContextUuid($c->contextUuid)??$c;}
    private function hydrate(?array $r):?GraphRelationContext{if(!$r)return null;try{$refs=json_decode((string)$r['evidence_refs_json'],true,512,JSON_THROW_ON_ERROR);return new GraphRelationContext(UuidCodec::fromBinary($r['context_uuid']),UuidCodec::fromBinary($r['edge_uuid']),(int)$r['source_revision'],(int)$r['target_revision'],(string)$r['scope_code'],(string)$r['scope_subject_type'],(string)$r['scope_subject_id'],(string)$r['provenance_class'],is_array($refs)?$refs:[],(string)$r['approval_fingerprint'],(string)$r['idempotency_key'],(int)$r['state']===1?GraphRelationContext::ACTIVE:GraphRelationContext::RETIRED,(int)$r['revision'],$r['created_at']??null,$r['updated_at']??null,$r['retired_at']??null);}catch(\Throwable){return null;}}
    private function fingerprint(GraphRelationContext $c):string{return hash('sha256',json_encode([$c->edgeUuid,$c->sourceRevision,$c->targetRevision,$c->scopeCode,$c->scopeSubjectType,$c->scopeSubjectId,$c->provenanceClass,$c->evidenceRefs,$c->approvalFingerprint],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));}
}
