<?php
declare(strict_types=1);
namespace NHK\Core\Infrastructure\Graph;
use NHK\Core\Contracts\Graph\GraphRepository;
use NHK\Core\Domain\Graph\{EdgeState,GraphEdge,GraphNode,NodeReference,PredicateDefinition};
use NHK\Core\Graph\Exception\{GraphNodeInUse,RelationAlreadyActive,RelationAlreadyRetired,RelationCardinalityViolation,RelationRevisionConflict};
use NHK\Core\Infrastructure\Database\WpdbTransactionManager;
use NHK\Core\Shared\Uuid\UuidCodec;

final class WpdbGraphRepository implements GraphRepository {
    private string $nodes; private string $predicates; private string $edges;
    public function __construct(private object $database) { $p=$database->prefix; $this->nodes=$p.'nhk_graph_nodes'; $this->predicates=$p.'nhk_graph_predicates'; $this->edges=$p.'nhk_graph_edges'; }
    public function resolveNode(NodeReference $reference): GraphNode {
        $this->database->query($this->database->prepare("INSERT IGNORE INTO {$this->nodes} (endpoint_type,endpoint_key,created_at) VALUES (%s,%s,%s)",$reference->endpoint_type,$reference->endpoint_key,$this->now()));
        $node=$this->findNode($reference); if(!$node) throw new \RuntimeException('GRAPH_NODE_RESOLUTION_FAILED'); return $node;
    }
    public function findNode(NodeReference $reference): ?GraphNode { $row=$this->database->get_row($this->database->prepare("SELECT id,endpoint_type,endpoint_key FROM {$this->nodes} WHERE endpoint_type=%s AND endpoint_key=%s LIMIT 1",$reference->endpoint_type,$reference->endpoint_key),ARRAY_A); return is_array($row)?new GraphNode((int)$row['id'],new NodeReference((string)$row['endpoint_type'],(string)$row['endpoint_key'])):null; }
    public function createEdge(GraphNode $source, PredicateDefinition $predicate, GraphNode $target): GraphEdge {
        $ownsTransaction = $this->beginIfNeeded();
        try {
            $existing=$this->findEdgeByNodes($source->internal_node_id,$predicate->key,$target->internal_node_id,true);
            if($existing && $existing->isActive()) { if ($ownsTransaction) $this->database->query('COMMIT'); return $existing; }
            if($existing && !$existing->isActive()) throw new RelationAlreadyRetired('Retired relation requires explicit reactivation.');
            if($predicate->outbound_cardinality==='ONE' && $this->countActive($source->internal_node_id,$predicate->key,'source')>0) throw new RelationCardinalityViolation('Outbound cardinality ONE violated.');
            if($predicate->inbound_cardinality==='ONE' && $this->countActive($target->internal_node_id,$predicate->key,'target')>0) throw new RelationCardinalityViolation('Inbound cardinality ONE violated.');
            $uuid=UuidCodec::newV7(); $now=$this->now(); $predicateId=$this->predicateId($predicate->key);
            $ok=$this->database->query($this->database->prepare("INSERT INTO {$this->edges} (edge_uuid,source_node_id,predicate_id,target_node_id,state,revision,created_at,updated_at) VALUES (UNHEX(%s),%d,%d,%d,1,1,%s,%s)",str_replace('-','',$uuid),$source->internal_node_id,$predicateId,$target->internal_node_id,$now,$now));
            if($ok===false) throw new \RuntimeException('GRAPH_EDGE_INSERT_FAILED'); $edge=$this->findEdgeByNodes($source->internal_node_id,$predicate->key,$target->internal_node_id); if ($ownsTransaction) $this->database->query('COMMIT'); if(!$edge) throw new \RuntimeException('GRAPH_EDGE_READBACK_FAILED'); return $edge;
        } catch(\Throwable $e) { if ($ownsTransaction) $this->database->query('ROLLBACK'); throw $e; }
    }
    public function findEdge(NodeReference $source,string $predicate,NodeReference $target): ?GraphEdge { $s=$this->findNode($source); $t=$this->findNode($target); if(!$s||!$t)return null; return $this->findEdgeByNodes($s->internal_node_id,$predicate,$t->internal_node_id); }
    public function findByUuid(string $uuid): ?GraphEdge { $row=$this->database->get_row($this->database->prepare("SELECT e.id,HEX(e.edge_uuid) edge_uuid,e.source_node_id,e.target_node_id,p.predicate_key,e.state,e.revision,e.created_at,e.updated_at,e.retired_at FROM {$this->edges} e JOIN {$this->predicates} p ON p.id=e.predicate_id WHERE e.edge_uuid=UNHEX(%s) LIMIT 1",str_replace('-','',$uuid)),ARRAY_A); return is_array($row)?$this->hydrate($row):null; }
    public function allEdges(bool $include_retired = true): array { $state = $include_retired ? '' : ' WHERE e.state=1'; $rows = $this->database->get_results("SELECT e.id,HEX(e.edge_uuid) edge_uuid,e.source_node_id,e.target_node_id,p.predicate_key,e.state,e.revision,e.created_at,e.updated_at,e.retired_at FROM {$this->edges} e JOIN {$this->predicates} p ON p.id=e.predicate_id{$state} ORDER BY e.id ASC", ARRAY_A) ?: []; return array_values(array_filter(array_map(fn (array $row): ?GraphEdge => $this->hydrate($row), $rows), static fn (?GraphEdge $edge): bool => $edge !== null)); }
    public function outgoing(GraphNode $source,?string $predicate,int $after_id,int $limit,bool $include_retired,?string $target_type=null): array { return $this->list($source->internal_node_id,$predicate,$after_id,$limit,$include_retired,true,$target_type); }
    public function incoming(GraphNode $target,?string $predicate,int $after_id,int $limit,bool $include_retired,?string $source_type=null): array { return $this->list($target->internal_node_id,$predicate,$after_id,$limit,$include_retired,false,$source_type); }
    public function retire(GraphEdge $edge,int $expected_revision): GraphEdge { return $this->changeState($edge,$expected_revision,EdgeState::RETIRED); }
    public function reactivate(GraphEdge $edge,int $expected_revision): GraphEdge { return $this->changeState($edge,$expected_revision,EdgeState::ACTIVE); }
    public function nodeHasEdges(GraphNode $node): bool { return (int)$this->database->get_var($this->database->prepare("SELECT COUNT(*) FROM {$this->edges} WHERE source_node_id=%d OR target_node_id=%d",$node->internal_node_id,$node->internal_node_id))>0; }
    public function deleteNode(GraphNode $node): void { if ($this->nodeHasEdges($node)) throw new GraphNodeInUse("Graph node still has edges."); $this->database->query($this->database->prepare("DELETE FROM {$this->nodes} WHERE id=%d",$node->internal_node_id)); }
    private function predicateId(string $key): int { $row=$this->database->get_row($this->database->prepare("SELECT id FROM {$this->predicates} WHERE predicate_key=%s",$key),ARRAY_A); if(!is_array($row)) { $this->database->query($this->database->prepare("INSERT IGNORE INTO {$this->predicates} (predicate_key,created_at) VALUES (%s,%s)",$key,$this->now())); $row=$this->database->get_row($this->database->prepare("SELECT id FROM {$this->predicates} WHERE predicate_key=%s",$key),ARRAY_A); } if(!is_array($row))throw new \RuntimeException('PREDICATE_MAPPING_FAILED'); return (int)$row['id']; }
    private function findEdgeByNodes(int $source,string $predicate,int $target,bool $lock=false): ?GraphEdge { $lockSql=$lock?' FOR UPDATE':''; $row=$this->database->get_row($this->database->prepare("SELECT e.id,HEX(e.edge_uuid) edge_uuid,e.source_node_id,e.target_node_id,p.predicate_key,e.state,e.revision,e.created_at,e.updated_at,e.retired_at FROM {$this->edges} e JOIN {$this->predicates} p ON p.id=e.predicate_id WHERE e.source_node_id=%d AND p.predicate_key=%s AND e.target_node_id=%d LIMIT 1{$lockSql}",$source,$predicate,$target),ARRAY_A); return is_array($row)?$this->hydrate($row):null; }
    private function countActive(int $node,string $predicate,string $side): int { $column=$side==='source'?'source_node_id':'target_node_id'; return (int)$this->database->get_var($this->database->prepare("SELECT COUNT(*) FROM {$this->edges} e JOIN {$this->predicates} p ON p.id=e.predicate_id WHERE e.{$column}=%d AND p.predicate_key=%s AND e.state=1 FOR UPDATE",$node,$predicate)); }
    private function list(int $node,?string $predicate,int $after,int $limit,bool $include,bool $out,?string $otherType=null): array { $column=$out?'source_node_id':'target_node_id'; $other=$out?'target_node_id':'source_node_id'; $state=$include?'':' AND e.state=1'; $pred=$predicate===null?'':' AND p.predicate_key='.$this->database->prepare('%s',$predicate); $type=$otherType===null?'':' AND other.endpoint_type='.$this->database->prepare('%s',$otherType); $rows=$this->database->get_results($this->database->prepare("SELECT e.id,HEX(e.edge_uuid) edge_uuid,e.source_node_id,e.target_node_id,p.predicate_key,e.state,e.revision,e.created_at,e.updated_at,e.retired_at FROM {$this->edges} e JOIN {$this->predicates} p ON p.id=e.predicate_id JOIN {$this->nodes} other ON other.id=e.{$other} WHERE e.{$column}=%d AND e.id>%d{$state}{$pred}{$type} ORDER BY e.id ASC LIMIT %d",$node,$after,$limit+1),ARRAY_A); $rows=is_array($rows)?$rows:[]; $next=null; if(count($rows)>$limit){array_pop($rows);$next=(int)end($rows)['id'];} $items=array_values(array_filter(array_map(fn(array $row)=>$this->hydrate($row),$rows),static fn(?GraphEdge $edge):bool=>$edge!==null)); return ['items'=>$items,'next_cursor'=>$next]; }
    private function changeState(GraphEdge $edge,int $expected,EdgeState $state): GraphEdge { $ownsTransaction=$this->beginIfNeeded(); try { $current=$this->findByUuid($edge->edge_uuid); if(!$current)throw new \RuntimeException('GRAPH_EDGE_NOT_FOUND'); if($current->revision!==$expected)throw new RelationRevisionConflict('Graph edge revision conflict.'); if($current->state===$state){if($ownsTransaction)$this->database->query('ROLLBACK'); throw $state===EdgeState::ACTIVE?new RelationAlreadyActive('Relation is already active.'):new RelationAlreadyRetired('Relation is already retired.');} $new=$expected+1; $retired=$state===EdgeState::RETIRED?$this->now():null; $this->database->query($this->database->prepare("UPDATE {$this->edges} SET state=%d,revision=%d,updated_at=%s,retired_at=%s WHERE edge_uuid=UNHEX(%s) AND revision=%d",$state->value,$new,$this->now(),$retired,str_replace('-','',$edge->edge_uuid),$expected)); $out=$this->findByUuid($edge->edge_uuid); if($ownsTransaction)$this->database->query('COMMIT'); if(!$out)throw new \RuntimeException('GRAPH_EDGE_READBACK_FAILED'); return $out; } catch(\Throwable $e){if($ownsTransaction)$this->database->query('ROLLBACK');throw $e;} }
    private function hydrate(array $row): ?GraphEdge { try{$source=$this->nodeById((int)$row['source_node_id']);$target=$this->nodeById((int)$row['target_node_id']);$edgeUuid=(string)$row['edge_uuid'];if(preg_match('/^[0-9a-f]{32}$/i',$edgeUuid))$edgeUuid=UuidCodec::fromBinary(hex2bin($edgeUuid));return new GraphEdge(strtolower($edgeUuid),$source,(string)$row['predicate_key'],$target,EdgeState::from((int)$row['state']),(int)$row['revision'],(string)$row['created_at'],(string)$row['updated_at'],isset($row['retired_at'])?(string)$row['retired_at']:null);}catch(\Throwable){return null;} }
    private function nodeById(int $id): GraphNode { $row=$this->database->get_row($this->database->prepare("SELECT id,endpoint_type,endpoint_key FROM {$this->nodes} WHERE id=%d",$id),ARRAY_A); if(!is_array($row))throw new \RuntimeException('GRAPH_NODE_NOT_FOUND'); return new GraphNode($id,new NodeReference((string)$row['endpoint_type'],(string)$row['endpoint_key'])); }
    private function beginIfNeeded(): bool { if (WpdbTransactionManager::isActive($this->database)) return false; if ($this->database->query('START TRANSACTION') === false) throw new \RuntimeException('GRAPH_TRANSACTION_BEGIN_FAILED'); return true; }
    private function now(): string { return gmdate('Y-m-d H:i:s.u'); }
}
