<?php
declare(strict_types=1);
namespace NHK\Core\Infrastructure\Dictionary;
use NHK\Core\Contracts\Dictionary\DictionaryLexicalRelationRepository;
use NHK\Core\Domain\Dictionary\DictionaryLexicalRelation as R;
use NHK\Core\Shared\Uuid\UuidCodec;
final class WpdbDictionaryLexicalRelationRepository implements DictionaryLexicalRelationRepository
{
    private string $table;
    public function __construct(private object $database){$this->table=$database->prefix.'nhk_dictionary_lexical_relations';}
    public function create(R $r):R{$e=$this->findByIdempotencyKey($r->idempotencyKey);if($e){if($this->fingerprint($e)===$this->fingerprint($r))return $e;throw new \RuntimeException('DICTIONARY_LEXICAL_RELATION_IDEMPOTENCY_CONFLICT');}$now=gmdate('Y-m-d H:i:s.u');$ok=$this->database->query($this->database->prepare("INSERT INTO {$this->table} (relation_uuid,source_entry_uuid,source_sense_uuid,target_entry_uuid,target_sense_uuid,relation_kind,provenance_json,idempotency_key,state,revision,created_at,updated_at) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,1,1,%s,%s)",UuidCodec::toBinary($r->relationUuid),UuidCodec::toBinary($r->sourceEntryUuid),$r->sourceSenseUuid?UuidCodec::toBinary($r->sourceSenseUuid):null,UuidCodec::toBinary($r->targetEntryUuid),$r->targetSenseUuid?UuidCodec::toBinary($r->targetSenseUuid):null,$r->kind,wp_json_encode($r->provenance),$r->idempotencyKey,$now,$now));if($ok===false)throw new \RuntimeException('DICTIONARY_LEXICAL_RELATION_CREATE_FAILED');return $this->findByUuid($r->relationUuid)??$r;}
    public function findByUuid(string $uuid):?R{return $this->hydrate($this->database->get_row($this->database->prepare("SELECT * FROM {$this->table} WHERE relation_uuid=%s LIMIT 1",UuidCodec::toBinary($uuid)),ARRAY_A));}
    public function findByIdempotencyKey(string $key):?R{return $this->hydrate($this->database->get_row($this->database->prepare("SELECT * FROM {$this->table} WHERE idempotency_key=%s LIMIT 1",$key),ARRAY_A));}
    public function update(R $r,int $expectedRevision):R{$ok=$this->database->query($this->database->prepare("UPDATE {$this->table} SET provenance_json=%s,revision=revision+1,updated_at=%s WHERE relation_uuid=%s AND revision=%d",wp_json_encode($r->provenance),gmdate('Y-m-d H:i:s.u'),UuidCodec::toBinary($r->relationUuid),$expectedRevision));if($ok!==1)throw new \RuntimeException('DICTIONARY_LEXICAL_RELATION_REVISION_CONFLICT');return $this->findByUuid($r->relationUuid)??$r;}
    public function retire(R $r,int $expectedRevision):R{return $this->lifecycle($r,$expectedRevision,0,gmdate('Y-m-d H:i:s.u'));}
    public function reactivate(R $r,int $expectedRevision):R{return $this->lifecycle($r,$expectedRevision,1,null);}
    private function lifecycle(R $r,int $expected,int $state,?string $retired):R{$ok=$this->database->query($this->database->prepare("UPDATE {$this->table} SET state=%d,revision=revision+1,updated_at=%s,retired_at=%s WHERE relation_uuid=%s AND revision=%d",$state,gmdate('Y-m-d H:i:s.u'),$retired,UuidCodec::toBinary($r->relationUuid),$expected));if($ok!==1)throw new \RuntimeException('DICTIONARY_LEXICAL_RELATION_REVISION_CONFLICT');return $this->findByUuid($r->relationUuid)??$r;}
    public function listForEntry(string $entryUuid,int $afterId=0,int $limit=100,bool $includeRetired=false):array{$limit=max(1,min(200,$limit));$state=$includeRetired?'':' AND state=1';$rows=$this->database->get_results($this->database->prepare("SELECT * FROM {$this->table} WHERE (source_entry_uuid=%s OR target_entry_uuid=%s) AND id>%d{$state} ORDER BY id LIMIT %d",UuidCodec::toBinary($entryUuid),UuidCodec::toBinary($entryUuid),$afterId,$limit+1),ARRAY_A)?:[];$items=array_values(array_filter(array_map(fn(array $row):?R=>$this->hydrate($row),$rows)));$next=count($items)>$limit?(int)$rows[$limit-1]['id']:null;return ['items'=>array_slice($items,0,$limit),'next_cursor'=>$next];}
    private function hydrate(?array $r):?R{if(!$r)return null;try{$p=json_decode((string)$r['provenance_json'],true,512,JSON_THROW_ON_ERROR);return new R(UuidCodec::fromBinary($r['relation_uuid']),UuidCodec::fromBinary($r['source_entry_uuid']),$r['source_sense_uuid']!==null?UuidCodec::fromBinary($r['source_sense_uuid']):null,UuidCodec::fromBinary($r['target_entry_uuid']),$r['target_sense_uuid']!==null?UuidCodec::fromBinary($r['target_sense_uuid']):null,(string)$r['relation_kind'],is_array($p)?$p:[],(string)$r['idempotency_key'],(int)$r['state']===1?R::ACTIVE:R::RETIRED,(int)$r['revision'],$r['created_at']??null,$r['updated_at']??null,$r['retired_at']??null);}catch(\Throwable){return null;}}
    private function fingerprint(R $r):string{return hash('sha256',json_encode([$r->sourceEntryUuid,$r->sourceSenseUuid,$r->targetEntryUuid,$r->targetSenseUuid,$r->kind,$r->provenance],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));}
}
