<?php
declare(strict_types=1);

namespace NHK\Core\Domain\Article;

enum ArticleIngestOutcome: string
{
    case COMPLETED = 'COMPLETED';
    case SEMANTIC_PREFLIGHT_REJECTED = 'SEMANTIC_PREFLIGHT_REJECTED';
    case GOVERNANCE_PENDING = 'GOVERNANCE_PENDING';
    case GOVERNANCE_REJECTED = 'GOVERNANCE_REJECTED';
    case SEMANTIC_APPLY_FAILED = 'SEMANTIC_APPLY_FAILED';
    case VERIFICATION_FAILED = 'VERIFICATION_FAILED';
    case STALE_SEMANTIC_REVISION = 'STALE_SEMANTIC_REVISION';
    case IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT';
    case DEPENDENCY_UNAVAILABLE = 'DEPENDENCY_UNAVAILABLE';
    case RECONCILIATION_CONFLICT = 'RECONCILIATION_CONFLICT';
    case UNSUPPORTED_OPERATION = 'UNSUPPORTED_OPERATION';
}
