<?php
declare(strict_types=1);
namespace NHK\Core\Domain\Dictionary;
use NHK\Core\Shared\Uuid\UuidCodec;
final readonly class DictionaryLexicalRelation
{
    public const RELATED='RELATED'; public const SAME_TERM_FAMILY='SAME_TERM_FAMILY'; public const BROADER='BROADER'; public const NARROWER='NARROWER'; public const NEAR_SYNONYM='NEAR_SYNONYM'; public const ACTIVE='ACTIVE'; public const RETIRED='RETIRED';
    public function __construct(public string $relationUuid, public string $sourceEntryUuid, public ?string $sourceSenseUuid, public string $targetEntryUuid, public ?string $targetSenseUuid, public string $kind, public array $provenance, public string $idempotencyKey, public string $state=self::ACTIVE, public int $revision=1, public ?string $createdAt=null, public ?string $updatedAt=null, public ?string $retiredAt=null)
    { foreach([$relationUuid,$sourceEntryUuid,$targetEntryUuid] as $id) if(!UuidCodec::isValid($id)) throw new \InvalidArgumentException('DICTIONARY_LEXICAL_RELATION_UUID_INVALID'); foreach([$sourceSenseUuid,$targetSenseUuid] as $id) if($id!==null&&!UuidCodec::isValid($id)) throw new \InvalidArgumentException('DICTIONARY_LEXICAL_RELATION_SENSE_UUID_INVALID'); if(!in_array($kind,[self::RELATED,self::SAME_TERM_FAMILY,self::BROADER,self::NARROWER,self::NEAR_SYNONYM],true)) throw new \InvalidArgumentException('DICTIONARY_LEXICAL_RELATION_KIND_INVALID'); if($idempotencyKey==='') throw new \InvalidArgumentException('DICTIONARY_LEXICAL_RELATION_IDEMPOTENCY_REQUIRED'); }
    public static function create(string $relationUuid,string $sourceEntryUuid,?string $sourceSenseUuid,string $targetEntryUuid,?string $targetSenseUuid,string $kind,array $provenance,string $idempotencyKey):self { return new self($relationUuid,$sourceEntryUuid,$sourceSenseUuid,$targetEntryUuid,$targetSenseUuid,$kind,$provenance,$idempotencyKey); }
    public function retired(int $expectedRevision):self { if($this->revision!==$expectedRevision) throw new \RuntimeException('DICTIONARY_LEXICAL_RELATION_REVISION_CONFLICT'); return new self($this->relationUuid,$this->sourceEntryUuid,$this->sourceSenseUuid,$this->targetEntryUuid,$this->targetSenseUuid,$this->kind,$this->provenance,$this->idempotencyKey,self::RETIRED,$expectedRevision+1,$this->createdAt,gmdate('Y-m-d H:i:s.u'),gmdate('Y-m-d H:i:s.u')); }
    public function reactivated(int $expectedRevision):self { if($this->revision!==$expectedRevision) throw new \RuntimeException('DICTIONARY_LEXICAL_RELATION_REVISION_CONFLICT'); return new self($this->relationUuid,$this->sourceEntryUuid,$this->sourceSenseUuid,$this->targetEntryUuid,$this->targetSenseUuid,$this->kind,$this->provenance,$this->idempotencyKey,self::ACTIVE,$expectedRevision+1,$this->createdAt,gmdate('Y-m-d H:i:s.u'),null); }
    public function toArray():array { return ['relation_uuid'=>$this->relationUuid,'source_entry_uuid'=>$this->sourceEntryUuid,'source_sense_uuid'=>$this->sourceSenseUuid,'target_entry_uuid'=>$this->targetEntryUuid,'target_sense_uuid'=>$this->targetSenseUuid,'relation_kind'=>$this->kind,'provenance'=>$this->provenance,'idempotency_key'=>$this->idempotencyKey,'state'=>$this->state,'revision'=>$this->revision,'created_at'=>$this->createdAt,'updated_at'=>$this->updatedAt,'retired_at'=>$this->retiredAt]; }
}
