<?php
declare(strict_types=1);
if (!defined('ABSPATH')) exit;

$context = is_array($GLOBALS['nhk_core_dictionary_context'] ?? null) ? $GLOBALS['nhk_core_dictionary_context'] : [];
$mode = (string) ($context['mode'] ?? '');
$result = is_array($context['result'] ?? null) ? $context['result'] : [];
$search = trim((string) ($result['query'] ?? ''));
$activeInitial = trim((string) ($result['initial'] ?? ''));
$items = array_values(array_filter((array) ($result['items'] ?? []), static fn (mixed $item): bool => is_array($item) && trim((string) ($item['title'] ?? '')) !== '' && trim((string) ($item['url'] ?? '')) !== ''));
$groups = [];
foreach ($items as $item) $groups[nhk_v3_dictionary_initial((string) $item['title'])][] = $item;
uksort($groups, static fn (string $a, string $b): int => strnatcasecmp($a, $b));
get_header();
?>
<main id="main-content" class="site-main nhk-dictionary">
    <div class="breadcrumbs" aria-label="Đường dẫn"><ol>
        <li><a href="<?php echo esc_url(home_url('/')); ?>">Trang chủ</a></li>
        <?php if ($mode === 'detail' && is_array($result['item'] ?? null)): ?><li><a href="<?php echo esc_url(home_url('/tu-dien/')); ?>">Từ điển</a></li><li><span><?php echo esc_html((string) ($result['item']['title'] ?? '')); ?></span></li>
        <?php else: ?><li><span>Từ điển</span></li><?php endif; ?>
    </ol></div>

<?php if ($mode === 'hub'): ?>
    <header class="archive-intro"><p class="eyebrow">Tra cứu nhanh</p><h1>Từ điển đồng hồ cổ</h1><p class="section-deck">Tra cứu thuật ngữ kỹ thuật, tên gọi quốc tế và cách gọi trong giới sưu tầm đồng hồ.</p>
        <form class="dictionary-search" method="get" action="<?php echo esc_url(home_url('/tu-dien/')); ?>"><label for="dictionary-search-input">Tìm trong từ điển</label><div><input id="dictionary-search-input" name="q" type="search" value="<?php echo esc_attr($search); ?>" placeholder="Tìm thuật ngữ..."><button type="submit">Tra cứu</button></div></form>
    </header>
    <?php if ($search !== '' && $items === []): ?><p class="dictionary-result-status" role="status">Không tìm thấy thuật ngữ phù hợp với “<?php echo esc_html($search); ?>”.</p><?php endif; ?>
    <?php if ($activeInitial !== '' && $items === [] && $search === ''): ?><p class="dictionary-result-status" role="status">Không có thuật ngữ bắt đầu bằng “<?php echo esc_html($activeInitial); ?>”.</p><?php endif; ?>
    <?php if ($items === [] && $search === '' && $activeInitial === ''): ?><div class="empty dictionary-empty"><h2>Từ điển đang được biên tập</h2><p>Chưa có thuật ngữ đã được phát hành công khai.</p><nav class="dictionary-discovery" aria-label="Khám phá thêm"><?php foreach (nhk_v3_navigation_items() as $label => $path): if (!in_array($label, ['Từ điển'], true)): ?><a href="<?php echo esc_url(home_url($path)); ?>"><?php echo esc_html($label); ?> <span aria-hidden="true">→</span></a><?php endif; endforeach; ?></nav></div>
    <?php else: ?><nav class="dictionary-index" aria-label="Tra cứu theo chữ cái"><?php foreach (array_keys($groups) as $initial): ?><a href="#dictionary-<?php echo esc_attr(nhk_v3_dictionary_anchor((string) $initial)); ?>"><?php echo esc_html((string) $initial); ?></a><?php endforeach; ?></nav><div class="dictionary-groups"><?php foreach ($groups as $initial => $group): ?><section id="dictionary-<?php echo esc_attr(nhk_v3_dictionary_anchor((string) $initial)); ?>" class="dictionary-group"><div class="section-head"><div><p class="eyebrow">Nhóm thuật ngữ</p><h2><?php echo esc_html((string) $initial); ?></h2></div></div><div class="dictionary-grid"><?php foreach ($group as $item): $image = is_array($item['image'] ?? null) ? $item['image'] : []; $visual = nhk_v3_media_presentation($image); $itemUrl = trim((string) ($item['url'] ?? '')); ?><article class="dictionary-card"><div class="dictionary-card-body"><p class="eyebrow"><?php echo esc_html(nhk_v3_public_copy((string) ($item['term_type'] ?? 'Thuật ngữ'))); ?></p><h3><?php if ($itemUrl !== ''): ?><a href="<?php echo esc_url($itemUrl); ?>"><?php echo esc_html((string) $item['title']); ?></a><?php else: ?><?php echo esc_html((string) $item['title']); ?><?php endif; ?></h3><?php if (trim((string) ($item['description'] ?? '')) !== ''): ?><p><?php echo esc_html(wp_trim_words((string) $item['description'], 24)); ?></p><?php endif; ?></div><?php if ($visual['url'] !== '' && $itemUrl !== ''): ?><a class="dictionary-card-image" href="<?php echo esc_url($itemUrl); ?>"><img src="<?php echo esc_url($visual['url']); ?>" alt="<?php echo esc_attr((string) ($image['alt'] ?? $item['title'])); ?>" loading="lazy" decoding="async"></a><?php endif; ?></article><?php endforeach; ?></div></section><?php endforeach; ?></div><?php endif; ?>

<?php elseif ($mode === 'detail' && is_array($result['item'] ?? null)): $item = $result['item']; $aliases = array_values(array_filter((array) ($item['labels'] ?? []), static fn (mixed $label): bool => is_array($label) && !in_array((string) ($label['kind'] ?? ''), ['PREFERRED', 'HIDDEN'], true))); $scopes = array_values(array_filter(array_map(static fn (mixed $scope): string => nhk_v3_dictionary_scope_label((string) $scope), (array) ($item['usage_scope'] ?? [])))); $image = is_array($item['image'] ?? null) ? $item['image'] : []; $visual = nhk_v3_media_presentation($image); ?>
    <article class="dictionary-entry"><header class="archive-intro"><p class="eyebrow"><?php echo esc_html(nhk_v3_public_copy((string) ($item['term_type'] ?? 'Thuật ngữ'))); ?></p><h1><?php echo esc_html((string) ($item['title'] ?? '')); ?></h1></header>
        <div class="dictionary-entry-layout"><?php if ($visual['url'] !== ''): ?><figure class="dictionary-entry-image"><img src="<?php echo esc_url($visual['url']); ?>" alt="<?php echo esc_attr((string) ($image['alt'] ?? $item['title'])); ?>" loading="lazy" decoding="async"></figure><?php endif; ?><div class="dictionary-entry-copy">
        <?php if (is_array($item['senses'] ?? null) && $item['senses'] !== []): ?><section class="dictionary-sense-packets">
            <?php foreach ($item['senses'] as $sense): $owner = is_array($sense['canonical_owner'] ?? null) ? $sense['canonical_owner'] : []; $groupsPacket = ['knowledge' => 'Tri thức', 'semantic_relations' => 'Quan hệ kỹ thuật', 'media' => 'Hình ảnh', 'videos' => 'Video', 'articles' => 'Bài viết', 'brands' => 'Thương hiệu', 'models' => 'Mẫu liên quan', 'specimens' => 'Hiện vật liên quan', 'related_terms' => 'Thuật ngữ nên xem tiếp']; ?>
                <article><h2>Chủ thể tương ứng</h2><?php if (trim((string) ($sense['description'] ?? '')) !== ''): ?><p><?php echo esc_html((string) ($sense['description'] ?? '')); ?></p><?php endif; ?>
                <?php if ($owner !== [] && trim((string) ($owner['url'] ?? '')) !== ''): ?><p><a href="<?php echo esc_url((string) $owner['url']); ?>"><?php echo esc_html((string) ($owner['title'] ?? $owner['name'] ?? '')); ?></a></p><?php endif; ?>
                <?php foreach ($groupsPacket as $key => $heading): $values = $key === 'related_terms' ? (array) ($sense[$key] ?? []) : (array) (($sense[$key]['items'] ?? [])); if ($values === []) continue; ?><section><h3><?php echo esc_html($heading); ?></h3><ul><?php foreach ($values as $value): if (!is_array($value)) continue; ?><li><?php if (trim((string) ($value['url'] ?? '')) !== ''): ?><a href="<?php echo esc_url((string) $value['url']); ?>"><?php echo esc_html((string) ($value['title'] ?? $value['name'] ?? '')); ?></a><?php else: ?><?php echo esc_html((string) ($value['title'] ?? $value['name'] ?? '')); ?><?php endif; ?></li><?php endforeach; ?></ul></section><?php endforeach; ?></article>
            <?php endforeach; ?></section><?php endif; ?>
        <?php if ($aliases !== []): ?><section><h2>Cách gọi khác</h2><ul><?php foreach ($aliases as $label): ?><li><?php echo esc_html((string) ($label['label'] ?? '')); ?><?php $kind = nhk_v3_dictionary_label_kind((string) ($label['kind'] ?? '')); if ($kind !== ''): ?> <span class="dictionary-label-kind"><?php echo esc_html($kind); ?></span><?php endif; ?></li><?php endforeach; ?></ul></section><?php endif; ?>
        <?php if (is_array($item['forms'] ?? null) && $item['forms'] !== []): ?><section><h2>Các dạng từ</h2><ul><?php foreach ($item['forms'] as $form): if (!is_array($form)) continue; ?><li><?php echo esc_html((string) ($form['form'] ?? '')); ?><?php if (trim((string) ($form['kind'] ?? '')) !== ''): ?> <span class="dictionary-label-kind"><?php echo esc_html((string) $form['kind']); ?></span><?php endif; ?></li><?php endforeach; ?></ul></section><?php endif; ?>
        <?php if ($scopes !== []): ?><section><h2>Phạm vi sử dụng</h2><p><?php echo esc_html(implode(', ', $scopes)); ?></p></section><?php endif; ?>
        <?php $mentions = is_array($item['mentions'] ?? null) ? $item['mentions'] : []; if (($mentions['groups'] ?? []) !== []): ?><section class="dictionary-mentions"><h2>Nội dung có nhắc đến “<?php echo esc_html((string) ($item['title'] ?? '')); ?>”</h2><?php foreach ((array) $mentions['groups'] as $kind => $mentionItems): if ($mentionItems === []) continue; ?><h3><?php echo esc_html(['ARTICLE' => 'Bài viết có nhắc đến', 'KNOWLEDGE' => 'Tri thức có nhắc đến', 'MEDIA' => 'Hình ảnh có nhắc đến', 'VIDEO' => 'Video có nhắc đến'][$kind] ?? 'Nội dung có nhắc đến'); ?></h3><ul><?php foreach ($mentionItems as $mention): if (!is_array($mention)) continue; ?><li><?php if (trim((string) ($mention['url'] ?? '')) !== ''): ?><a href="<?php echo esc_url((string) $mention['url']); ?>"><?php echo esc_html((string) ($mention['title'] ?? '')); ?></a><?php else: ?><?php echo esc_html((string) ($mention['title'] ?? '')); ?><?php endif; ?></li><?php endforeach; ?></ul><?php endforeach; ?></section><?php endif; ?>
        </div></div>
    </article>
<?php endif; ?></main><?php get_footer();
