<?php
declare(strict_types=1);
if (!defined('ABSPATH')) exit;
$context = is_array($GLOBALS['nhk_core_dictionary_context'] ?? null) ? $GLOBALS['nhk_core_dictionary_context'] : [];
$mode = (string) ($context['mode'] ?? '');
$result = is_array($context['result'] ?? null) ? $context['result'] : [];
$items = array_values(array_filter((array) ($result['items'] ?? []), static fn (mixed $item): bool => is_array($item) && trim((string) ($item['title'] ?? '')) !== '' && trim((string) ($item['url'] ?? '')) !== ''));
$groups = [];
foreach ($items as $item) $groups[nhk_v3_dictionary_initial((string) $item['title'])][] = $item;
uksort($groups, static fn (string $a, string $b): int => strnatcasecmp($a, $b));
get_header();
?>
<main id="main-content" class="site-main nhk-dictionary"><div class="breadcrumbs" aria-label="Đường dẫn"><ol><li><a href="<?php echo esc_url(home_url('/')); ?>">Trang chủ</a></li><li><span>Từ điển</span></li></ol></div>
<?php if ($mode === 'hub'): ?>
  <header class="archive-intro"><p class="eyebrow">Tra cứu nhanh</p><h1>Từ điển đồng hồ cổ</h1><p class="section-deck">Thuật ngữ kỹ thuật, cách gọi dân gian và những khái niệm đã được biên tập để tra cứu công khai.</p></header>
  <?php if ($items === []): ?><div class="empty dictionary-empty"><h2>Từ điển đang được biên tập</h2><p>Chưa có thuật ngữ đã được phát hành công khai.</p><nav class="dictionary-discovery" aria-label="Khám phá thêm"><?php foreach (nhk_v3_navigation_items() as $label => $path): if (!in_array($label, ['Từ điển'], true)): ?><a href="<?php echo esc_url(home_url($path)); ?>"><?php echo esc_html($label); ?> <span aria-hidden="true">→</span></a><?php endif; endforeach; ?></nav></div>
  <?php else: ?><nav class="dictionary-index" aria-label="Tra cứu theo chữ cái"><?php foreach (array_keys($groups) as $initial): ?><a href="#dictionary-<?php echo esc_attr(nhk_v3_dictionary_anchor($initial)); ?>"><?php echo esc_html($initial); ?></a><?php endforeach; ?></nav><div class="dictionary-groups"><?php foreach ($groups as $initial => $group): ?><section id="dictionary-<?php echo esc_attr(nhk_v3_dictionary_anchor($initial)); ?>" class="dictionary-group"><div class="section-head"><div><p class="eyebrow">Nhóm thuật ngữ</p><h2><?php echo esc_html($initial); ?></h2></div></div><div class="dictionary-grid"><?php foreach ($group as $item): $image = is_array($item['image'] ?? null) ? $item['image'] : []; $visual = nhk_v3_media_presentation($image); ?><article class="dictionary-card"><div class="dictionary-card-body"><p class="eyebrow"><?php echo esc_html(nhk_v3_public_copy((string) ($item['term_type'] ?? 'Thuật ngữ'))); ?></p><h3><a href="<?php echo esc_url($item['url']); ?>"><?php echo esc_html((string) $item['title']); ?></a></h3><?php if (trim((string) ($item['description'] ?? '')) !== ''): ?><p><?php echo esc_html(wp_trim_words((string) $item['description'], 24)); ?></p><?php endif; ?></div><?php if ($visual['url'] !== ''): ?><a class="dictionary-card-image" href="<?php echo esc_url($item['url']); ?>"><img src="<?php echo esc_url($visual['url']); ?>" alt="<?php echo esc_attr((string) ($image['alt'] ?? $item['title'])); ?>" loading="lazy" decoding="async"<?php if ($visual['srcset'] !== ''): ?> srcset="<?php echo esc_attr($visual['srcset']); ?>" sizes="<?php echo esc_attr($visual['sizes'] !== '' ? $visual['sizes'] : '(max-width: 48rem) 100vw, 25vw'); ?>"<?php endif; ?><?php if ($visual['width'] > 0): ?> width="<?php echo esc_attr((string) $visual['width']); ?>"<?php endif; ?><?php if ($visual['height'] > 0): ?> height="<?php echo esc_attr((string) $visual['height']); ?>"<?php endif; ?>></a><?php endif; ?></article><?php endforeach; ?></div></section><?php endforeach; ?></div><?php endif; ?>
<?php elseif ($mode === 'detail' && is_array($result['item'] ?? null)): $item = $result['item']; $aliases = array_values(array_filter((array) ($item['labels'] ?? []), static fn (mixed $label): bool => is_array($label) && !in_array((string) ($label['kind'] ?? ''), ['PREFERRED', 'HIDDEN'], true))); $scopes = array_values(array_filter(array_map(static fn (mixed $scope): string => nhk_v3_dictionary_scope_label((string) $scope), (array) ($item['usage_scope'] ?? [])))); ?>
  <?php $image = is_array($item['image'] ?? null) ? $item['image'] : []; $visual = nhk_v3_media_presentation($image); ?><article class="dictionary-entry"><header class="archive-intro"><p class="eyebrow"><?php echo esc_html(nhk_v3_public_copy((string) ($item['term_type'] ?? 'Thuật ngữ'))); ?></p><h1><?php echo esc_html((string) ($item['title'] ?? '')); ?></h1></header><div class="dictionary-entry-layout"><?php if ($visual['url'] !== ''): ?><figure class="dictionary-entry-image"><img src="<?php echo esc_url($visual['url']); ?>" alt="<?php echo esc_attr((string) ($image['alt'] ?? $item['title'])); ?>" loading="lazy" decoding="async"<?php if ($visual['srcset'] !== ''): ?> srcset="<?php echo esc_attr($visual['srcset']); ?>" sizes="<?php echo esc_attr($visual['sizes'] !== '' ? $visual['sizes'] : '(max-width: 48rem) 100vw, 360px'); ?>"<?php endif; ?><?php if ($visual['width'] > 0): ?> width="<?php echo esc_attr((string) $visual['width']); ?>"<?php endif; ?><?php if ($visual['height'] > 0): ?> height="<?php echo esc_attr((string) $visual['height']); ?>"<?php endif; ?>></figure><?php endif; ?><div class="dictionary-entry-copy"><p class="dictionary-definition"><?php echo esc_html((string) ($item['description'] ?? '')); ?></p><?php if ($aliases !== []): ?><section><h2>Cách gọi khác</h2><ul><?php foreach ($aliases as $label): $kind = nhk_v3_dictionary_label_kind((string) ($label['kind'] ?? '')); ?><li><?php echo esc_html((string) ($label['label'] ?? '')); ?><?php if ($kind !== ''): ?> <span class="dictionary-label-kind"><?php echo esc_html($kind); ?></span><?php endif; ?></li><?php endforeach; ?></ul></section><?php endif; ?><?php if ($scopes !== []): ?><section><h2>Phạm vi sử dụng</h2><p><?php echo esc_html(implode(', ', $scopes)); ?></p></section><?php endif; ?></div></div></article>
<?php endif; ?></main><?php get_footer();
