<?php
declare(strict_types=1);
if (!defined('ABSPATH')) exit;

$context = is_array($GLOBALS['nhk_core_dictionary_context'] ?? null) ? $GLOBALS['nhk_core_dictionary_context'] : [];
$mode = (string) ($context['mode'] ?? '');
$result = is_array($context['result'] ?? null) ? $context['result'] : [];
$search = trim((string) ($result['query'] ?? ''));
$activeInitial = trim((string) ($result['initial'] ?? ''));
$items = array_values(array_filter((array) ($result['items'] ?? []), static fn (mixed $item): bool => is_array($item) && trim((string) ($item['title'] ?? '')) !== '' && trim((string) ($item['url'] ?? '')) !== ''));
$pagination = is_array($result['pagination'] ?? null) ? $result['pagination'] : [];
$total = isset($pagination['total_count']) && $pagination['total_count'] !== null ? (int) $pagination['total_count'] : null;
$alphabet = array_values(array_filter((array) ($result['alphabet'] ?? []), static fn (mixed $bucket): bool => is_array($bucket) && trim((string) ($bucket['key'] ?? '')) !== ''));
$groups = [];
foreach ($items as $item) $groups[nhk_v3_dictionary_initial((string) $item['title'])][] = $item;
uksort($groups, static fn (string $a, string $b): int => strnatcasecmp($a, $b));
$facetLabels = ['brands' => 'Thương hiệu', 'clock_types' => 'Loại đồng hồ', 'configurations' => 'Cấu hình', 'movements' => 'Bộ máy', 'music' => 'Âm nhạc', 'countries' => 'Quốc gia', 'models' => 'Mẫu đồng hồ', 'variants' => 'Biến thể', 'specimens' => 'Hiện vật', 'components' => 'Linh kiện'];
$lexicalRelationLabels = ['BROADER' => 'Nhóm rộng hơn', 'NARROWER' => 'Dạng cụ thể', 'NEAR_SYNONYM' => 'Gần nghĩa', 'SAME_TERM_FAMILY' => 'Cùng nhóm thuật ngữ', 'RELATED' => 'Thuật ngữ liên quan'];
$publicUrl = static fn (mixed $url): string => nhk_v3_public_url($url);
$bucketItems = static function (mixed $bucket): array { return is_array($bucket) && in_array((string) ($bucket['status'] ?? ''), ['AVAILABLE_WITH_ITEMS', 'AVAILABLE'], true) && is_array($bucket['items'] ?? null) ? $bucket['items'] : []; };
$itemTitle = static fn (array $item): string => trim((string) ($item['title'] ?? $item['name'] ?? ''));

get_header();
?>
<main id="main-content" class="site-main nhk-dictionary">
    <div class="breadcrumbs" aria-label="Đường dẫn"><ol>
        <li><a href="<?php echo esc_url(home_url('/')); ?>">Trang chủ</a></li>
        <?php if ($mode === 'detail' && is_array($result['item'] ?? null)): ?><li><a href="<?php echo esc_url(home_url('/tu-dien/')); ?>">Từ điển</a></li><li><span><?php echo esc_html((string) ($result['item']['title'] ?? '')); ?></span></li>
        <?php else: ?><li><span>Từ điển</span></li><?php endif; ?>
    </ol></div>

<?php if ($mode === 'hub'): ?>
    <header class="archive-intro"><p class="eyebrow">Tra cứu nhanh</p><h1>Từ điển đồng hồ cổ</h1><p class="section-deck">Tra cứu thuật ngữ kỹ thuật, tên gọi quốc tế và cách gọi trong giới sưu tầm đồng hồ.</p>
        <form class="dictionary-search" method="get" action="<?php echo esc_url(home_url('/tu-dien/')); ?>"><label for="dictionary-search-input">Tìm trong từ điển</label><div><input id="dictionary-search-input" name="q" type="search" value="<?php echo esc_attr($search); ?>" placeholder="Tìm thuật ngữ..."><button type="submit">Tra cứu</button></div></form>
    </header>
    <div class="dictionary-browse-summary" role="status" aria-live="polite">
        <?php if ($search !== ''): ?><p>Kết quả cho “<?php echo esc_html($search); ?>”<?php if ($total !== null): ?> · <?php echo esc_html((string) $total); ?> thuật ngữ<?php endif; ?></p>
        <?php elseif ($activeInitial !== '' && $total !== null): ?><p><?php echo esc_html((string) $total); ?> thuật ngữ bắt đầu bằng <?php echo esc_html($activeInitial); ?></p>
        <?php elseif ($total !== null): ?><p><?php echo esc_html((string) $total); ?> thuật ngữ</p><?php else: ?><p>Danh sách thuật ngữ</p><?php endif; ?>
    </div>
    <nav class="dictionary-alphabet" aria-label="Tra cứu theo chữ cái">
        <?php foreach ($alphabet as $bucket): $key = (string) ($bucket['key'] ?? ''); $label = (string) ($bucket['label'] ?? $key); $count = (int) ($bucket['count'] ?? 0); $available = (bool) ($bucket['available'] ?? false); $active = ($activeInitial === '' && $key === 'ALL') || ($activeInitial !== '' && $key === $activeInitial); $href = add_query_arg(['initial' => $key === 'ALL' ? null : $key], home_url('/tu-dien/')); ?>
            <?php if (!$available && !$active): ?><span class="is-disabled" aria-disabled="true" title="Chưa có thuật ngữ"><?php echo esc_html($label); ?></span>
            <?php else: ?><a href="<?php echo esc_url((string) $href); ?>"<?php if ($active): ?> aria-current="true" class="is-active"<?php endif; ?>><?php echo esc_html($label); ?><?php if ($count > 0): ?><small><?php echo esc_html((string) $count); ?></small><?php endif; ?></a><?php endif; ?>
        <?php endforeach; ?>
    </nav>
    <?php if ($items === []): ?><div class="empty dictionary-empty"><h2><?php echo $search !== '' || $activeInitial !== '' ? 'Chưa có kết quả phù hợp' : 'Từ điển đang được biên tập'; ?></h2><p><?php echo $search !== '' ? 'Hãy thử một cách gọi khác.' : 'Chưa có thuật ngữ đã được phát hành công khai.'; ?></p></div>
    <?php else: ?><div class="dictionary-groups"><?php foreach ($groups as $initial => $group): ?><section id="dictionary-<?php echo esc_attr(nhk_v3_dictionary_anchor((string) $initial)); ?>" class="dictionary-group"><div class="section-head"><div><p class="eyebrow">Nhóm thuật ngữ</p><h2><?php echo esc_html((string) $initial); ?></h2></div></div><div class="dictionary-grid"><?php foreach ($group as $item): $itemUrl = $publicUrl($item['url'] ?? null); ?><article class="dictionary-card"><div class="dictionary-card-body"><p class="eyebrow"><?php echo esc_html(nhk_v3_public_copy((string) ($item['term_type'] ?? 'Thuật ngữ'))); ?></p><h3><a href="<?php echo esc_url($itemUrl); ?>"><?php echo esc_html((string) $item['title']); ?></a></h3><?php if (trim((string) ($item['description'] ?? '')) !== ''): ?><p><?php echo esc_html(wp_trim_words((string) $item['description'], 24)); ?></p><?php endif; ?></div></article><?php endforeach; ?></div></section><?php endforeach; ?></div>
        <?php if (($pagination['has_next'] ?? false) && trim((string) ($pagination['next_cursor'] ?? '')) !== ''): ?><nav class="dictionary-pagination" aria-label="Phân trang từ điển"><a href="<?php echo esc_url((string) add_query_arg(array_filter(['q' => $search, 'initial' => $activeInitial !== '' ? $activeInitial : null, 'cursor' => (string) $pagination['next_cursor']]), home_url('/tu-dien/'))); ?>">Trang sau <span aria-hidden="true">→</span></a></nav><?php endif; ?>
    <?php endif; ?>

<?php elseif ($mode === 'detail' && is_array($result['item'] ?? null)): $item = $result['item']; $senses = array_values(array_filter((array) ($item['senses'] ?? []), 'is_array')); $aliases = array_values(array_filter((array) ($item['labels'] ?? []), static fn (mixed $label): bool => is_array($label) && !in_array((string) ($label['kind'] ?? ''), ['PREFERRED', 'HIDDEN'], true))); ?>
    <article class="dictionary-entry">
        <header class="dictionary-lexical-hero"><p class="eyebrow">Thuật ngữ</p><h1><?php echo esc_html((string) ($item['title'] ?? '')); ?></h1><?php if (trim((string) ($item['description'] ?? '')) !== ''): ?><p class="dictionary-definition"><?php echo esc_html((string) $item['description']); ?></p><?php endif; ?></header>
        <?php if ($aliases !== [] || (array) ($item['forms'] ?? []) !== []): ?><section class="dictionary-detail-section"><h2>Các dạng từ</h2><div class="dictionary-form-list"><?php foreach (array_merge($aliases, (array) ($item['forms'] ?? [])) as $form): if (!is_array($form)) continue; $formText = (string) ($form['label'] ?? $form['form'] ?? ''); if ($formText === '') continue; ?><span><?php echo esc_html($formText); ?><?php $kind = nhk_v3_dictionary_label_kind((string) ($form['kind'] ?? '')); if ($kind !== ''): ?> <small><?php echo esc_html($kind); ?></small><?php endif; ?></span><?php endforeach; ?></div></section><?php endif; ?>
        <?php if (count($senses) > 1): ?><section class="dictionary-detail-section"><h2>Các nghĩa</h2><?php endif; ?>
        <?php foreach ($senses as $sense): $owner = is_array($sense['canonical_owner'] ?? null) ? $sense['canonical_owner'] : []; $ownerUrl = $publicUrl($owner['url'] ?? null); $facets = is_array($sense['relation_facets'] ?? null) ? $sense['relation_facets'] : []; $derived = is_array($sense['derived_entities'] ?? null) ? $sense['derived_entities'] : []; $mentions = is_array($item['mentions'] ?? null) ? $item['mentions'] : []; $semanticRelations = $bucketItems($sense['semantic_relations'] ?? []); ?>
            <section class="dictionary-sense dictionary-detail-section">
                <?php if (count($senses) > 1): ?><h3><?php echo esc_html((string) ($sense['title'] ?? '')); ?></h3><?php endif; ?>
                <?php if (count($senses) > 1 && trim((string) ($sense['description'] ?? '')) !== ''): ?><p class="dictionary-definition"><?php echo esc_html((string) $sense['description']); ?></p><?php endif; ?>
                <?php if ($ownerUrl !== ''): ?><div class="dictionary-owner"><p class="eyebrow">Hồ sơ chính</p><a href="<?php echo esc_url($ownerUrl); ?>"><?php echo esc_html((string) ($owner['title'] ?? $owner['name'] ?? 'Xem hồ sơ đầy đủ')); ?></a></div><?php endif; ?>
                <?php if ($semanticRelations !== []): ?><section><h3>Liên hệ đã được ghi nhận</h3><div class="dictionary-related-grid"><?php foreach ($semanticRelations as $relation): if (!is_array($relation)) continue; $relationTitle = $itemTitle($relation); $relationUrl = $publicUrl($relation['url'] ?? null); if ($relationTitle === '') continue; $direct = strtoupper((string) ($relation['origin']['kind'] ?? $relation['relationship_class'] ?? '')) === 'DIRECT'; ?><?php if ($relationUrl !== ''): ?><a class="dictionary-related-card" href="<?php echo esc_url($relationUrl); ?>"><?php else: ?><div class="dictionary-related-card" aria-disabled="true"><?php endif; ?><span><?php echo esc_html($direct ? 'Liên quan trực tiếp' : 'Liên quan mở rộng'); ?></span><strong><?php echo esc_html($relationTitle); ?></strong><?php echo $relationUrl !== '' ? '</a>' : '</div>'; ?><?php endforeach; ?></div></section><?php endif; ?>
                <?php foreach ($facetLabels as $facetKey => $facetLabel): $facetItems = $bucketItems($facets[$facetKey] ?? ($derived[$facetKey] ?? [])); if ($facetItems === []) continue; ?><section><h3><?php echo esc_html($facetLabel); ?></h3><div class="dictionary-related-grid"><?php foreach ($facetItems as $facetItem): if (!is_array($facetItem)) continue; $facetTitle = $itemTitle($facetItem); $facetUrl = $publicUrl($facetItem['url'] ?? null); if ($facetTitle === '') continue; ?><?php if ($facetUrl !== ''): ?><a class="dictionary-related-card" href="<?php echo esc_url($facetUrl); ?>"><?php else: ?><div class="dictionary-related-card" aria-disabled="true"><?php endif; ?><strong><?php echo esc_html($facetTitle); ?></strong><?php echo $facetUrl !== '' ? '</a>' : '</div>'; ?><?php endforeach; ?></div></section><?php endforeach; ?>
                <?php $knowledge = $bucketItems($sense['knowledge'] ?? []); if ($knowledge !== []): ?><section><h3>Tri thức liên quan</h3><div class="dictionary-knowledge-list"><?php foreach ($knowledge as $claim): if (!is_array($claim)) continue; $claimText = trim((string) ($claim['text'] ?? $claim['title'] ?? $claim['description'] ?? '')); if ($claimText !== ''): ?><p><?php echo esc_html($claimText); ?></p><?php endif; endforeach; ?></div></section><?php endif; ?>
                <?php $media = $bucketItems($sense['media'] ?? []); if ($media !== []): ?><section><h3>Hình ảnh</h3><div class="media-mosaic dictionary-gallery"><?php foreach ($media as $mediaItem): if (!is_array($mediaItem)) continue; $visual = nhk_v3_media_presentation($mediaItem); if ($visual['url'] === '') continue; $destination = nhk_v3_media_content_url($mediaItem); ?><figure class="media-figure"><?php if ($destination !== ''): ?><a href="<?php echo esc_url($destination); ?>"><?php endif; ?><img src="<?php echo esc_url($visual['url']); ?>" alt="<?php echo esc_attr((string) ($mediaItem['alt'] ?? $mediaItem['title'] ?? $item['title'])); ?>" loading="lazy" decoding="async"<?php if ($visual['srcset'] !== ''): ?> srcset="<?php echo esc_attr($visual['srcset']); ?>"<?php endif; ?><?php if ($visual['sizes'] !== ''): ?> sizes="<?php echo esc_attr($visual['sizes']); ?>"<?php endif; ?>><?php if ($destination !== ''): ?></a><?php endif; ?><figcaption><?php echo esc_html((string) ($mediaItem['title'] ?? 'Hình ảnh')); ?></figcaption></figure><?php endforeach; ?></div></section><?php endif; ?>
                <?php $videos = $bucketItems($sense['videos'] ?? []); if ($videos !== []): ?><section><h3>Video</h3><div class="video-card-grid"><?php foreach ($videos as $video): if (is_array($video)) get_template_part('template-parts/presentation/video-card', null, ['item' => $video]); endforeach; ?></div></section><?php endif; ?>
                <?php $articles = $bucketItems($sense['articles'] ?? []); if ($articles !== []): ?><section><h3>Bài viết liên quan</h3><div class="dictionary-related-grid"><?php foreach ($articles as $article): if (!is_array($article)) continue; $articleUrl = $publicUrl($article['url'] ?? null); $articleTitle = $itemTitle($article); if ($articleUrl === '' || $articleTitle === '') continue; ?><a class="dictionary-related-card" href="<?php echo esc_url($articleUrl); ?>"><span>Bài viết</span><strong><?php echo esc_html($articleTitle); ?></strong></a><?php endforeach; ?></div></section><?php endif; ?>
                <?php $relatedTerms = array_values(array_filter((array) ($sense['related_terms'] ?? []), 'is_array')); if ($relatedTerms !== []): ?><section><h3>Thuật ngữ liên quan</h3><div class="dictionary-related-grid"><?php foreach ($relatedTerms as $term): $termUrl = $publicUrl($term['url'] ?? null); $termTitle = $itemTitle($term); if ($termTitle === '') continue; $relationLabel = $lexicalRelationLabels[strtoupper((string) ($term['relation_kind'] ?? $term['kind'] ?? 'RELATED'))] ?? 'Thuật ngữ liên quan'; ?><?php if ($termUrl !== ''): ?><a class="dictionary-related-card" href="<?php echo esc_url($termUrl); ?>"><?php else: ?><div class="dictionary-related-card" aria-disabled="true"><?php endif; ?><span><?php echo esc_html($relationLabel); ?></span><strong><?php echo esc_html($termTitle); ?></strong><?php echo $termUrl !== '' ? '</a>' : '</div>'; ?><?php endforeach; ?></div></section><?php endif; ?>
                <?php if (($mentions['groups'] ?? []) !== []): ?><section class="dictionary-mentions"><h3>Nội dung có nhắc đến “<?php echo esc_html((string) ($item['title'] ?? '')); ?>”</h3><?php foreach ((array) $mentions['groups'] as $kind => $mentionItems): if ($mentionItems === []) continue; ?><h4><?php echo esc_html(['ARTICLE' => 'Bài viết có nhắc đến', 'KNOWLEDGE' => 'Tri thức có nhắc đến', 'MEDIA' => 'Hình ảnh có nhắc đến', 'VIDEO' => 'Video có nhắc đến'][$kind] ?? 'Nội dung có nhắc đến'); ?></h4><ul><?php foreach ($mentionItems as $mention): if (!is_array($mention)) continue; $mentionUrl = $publicUrl($mention['url'] ?? null); $mentionTitle = $itemTitle($mention); if ($mentionTitle === '') continue; ?><li><?php if ($mentionUrl !== ''): ?><a href="<?php echo esc_url($mentionUrl); ?>"><?php echo esc_html($mentionTitle); ?></a><?php else: ?><?php echo esc_html($mentionTitle); ?><?php endif; ?></li><?php endforeach; ?></ul><?php endforeach; ?></section><?php endif; ?>
            </section>
        <?php endforeach; ?>
        <?php if (count($senses) > 1): ?></section><?php endif; ?>
    </article>
<?php endif; ?></main><?php get_footer();
