<?php
$context = $GLOBALS['nhk_core_entity_context'] ?? null;
$labels = ['brand' => 'Thương hiệu', 'model' => 'Mẫu đồng hồ', 'variant' => 'Biến thể', 'movement' => 'Bộ máy', 'music' => 'Bản nhạc', 'component' => 'Linh kiện', 'classification' => 'Phân loại', 'specimen' => 'Hiện vật', 'product' => 'Sản phẩm'];
$type = is_array($context) ? (string) ($context['type'] ?? '') : '';
$label = $labels[$type] ?? 'Khám phá';
get_header();
?><main class="site-main entity-shell">
<?php if (is_array($context) && ($context['mode'] ?? '') === 'detail' && is_array($context['entity'] ?? null)): $entity = $context['entity']; ?>
  <p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">NHK</a> <span>/</span> <a href="<?php echo esc_url($context['archive_url']); ?>"><?php echo esc_html($label); ?></a></p>
  <header class="entity-header"><p class="eyebrow"><?php echo esc_html($label); ?></p><h1><?php echo esc_html($entity['name']); ?></h1><p class="entity-key"><?php echo esc_html($entity['stable_key']); ?></p></header>
  <div class="entity-layout"><section class="entity-overview"><h2>Hồ sơ</h2><p>Thông tin định danh canonical của <?php echo esc_html(strtolower($label)); ?> trong kho NHK.</p><dl class="entity-facts"><dt>Loại</dt><dd><?php echo esc_html($label); ?></dd><dt>Revision</dt><dd><?php echo esc_html((string) $entity['revision']); ?></dd><dt>Canonical ID</dt><dd><code><?php echo esc_html($entity['id']); ?></code></dd></dl></section><?php if (!empty($entity['payload'])): ?><section class="entity-facts-block"><h2>Thông tin semantic</h2><dl class="entity-facts"><?php foreach ($entity['payload'] as $key => $value): ?><dt><?php echo esc_html(ucwords(str_replace('_', ' ', (string) $key))); ?></dt><dd><?php echo esc_html(is_scalar($value) ? (string) $value : (string) wp_json_encode($value, JSON_UNESCAPED_UNICODE)); ?></dd><?php endforeach; ?></dl></section><?php endif; ?></div>
<?php $related = is_array($entity['related'] ?? null) ? $entity['related'] : []; foreach (['entities' => 'Liên quan', 'articles' => 'Bài viết liên quan', 'media' => 'Hình ảnh & media', 'videos' => 'Video liên quan'] as $group => $heading): if (!empty($related[$group])): ?><section class="related-section"><div class="section-head"><div><p class="eyebrow">NHK</p><h2><?php echo esc_html($heading); ?></h2></div></div><div class="related-grid"><?php foreach ($related[$group] as $item): ?><a class="related-card" href="<?php echo esc_url($item['url'] ?? '#'); ?>"><span class="related-type"><?php echo esc_html($item['type'] ?? ''); ?></span><strong><?php echo esc_html($item['title'] ?? ''); ?></strong></a><?php endforeach; ?></div></section><?php endif; endforeach; ?>
<?php elseif (is_array($context) && is_array($context['archive'] ?? null)): $archive = $context['archive']; ?>
  <header class="archive-intro entity-archive-intro"><p class="eyebrow"><?php echo esc_html($label); ?></p><h1>Khám phá <?php echo esc_html(strtolower($label)); ?></h1><p class="archive-summary">Các hồ sơ canonical đang hoạt động trong kho NHK.</p><form class="entity-filter" method="get" action="<?php echo esc_url($context['archive_url']); ?>"><label class="screen-reader-text" for="nhk-entity-q">Tìm trong <?php echo esc_attr(strtolower($label)); ?></label><input id="nhk-entity-q" name="nhk_entity_q" type="search" value="<?php echo esc_attr($archive['query']); ?>" placeholder="Tìm <?php echo esc_attr(strtolower($label)); ?>..."><button type="submit">Tìm</button></form></header>
  <?php if (!empty($archive['items'])): ?><div class="entity-grid"><?php foreach ($archive['items'] as $item): ?><article class="entity-card"><p class="eyebrow"><?php echo esc_html($label); ?></p><h2><a href="<?php echo esc_url(home_url('/' . $type . '/' . rawurlencode($item['stable_key']) . '/')); ?>"><?php echo esc_html($item['name']); ?></a></h2><p class="entity-card-key"><?php echo esc_html($item['stable_key']); ?></p></article><?php endforeach; ?></div><?php else: ?><div class="empty"><h2>Chưa có hồ sơ phù hợp</h2><p>Thử từ khóa khác hoặc quay lại sau khi dữ liệu canonical được bổ sung.</p></div><?php endif; ?>
  <?php $pages = (int) ceil($archive['total'] / max(1, $archive['per_page'])); if ($pages > 1): ?><nav class="entity-pagination" aria-label="Phân trang <?php echo esc_attr($label); ?>"><?php for ($i = 1; $i <= $pages; $i++): $url = home_url('/' . $type . ($i > 1 ? '/page/' . $i : '') . '/'); if ($archive['query'] !== '') $url = add_query_arg('nhk_entity_q', $archive['query'], $url); ?><a class="<?php echo $i === (int) $archive['page'] ? 'current' : ''; ?>" href="<?php echo esc_url($url); ?>"><?php echo esc_html((string) $i); ?></a><?php endfor; ?></nav><?php endif; ?>
<?php else: ?><div class="empty"><h1>Không thể tải hồ sơ</h1><p>Trang semantic hiện chưa sẵn sàng.</p></div><?php endif; ?></main><?php get_footer();
