<?php get_header(); ?><main class="site-main">
  <section class="hero"><p class="eyebrow">Kho tri thức và sưu tầm</p><h1>Mỗi chiếc đồng hồ<br><em>mang một câu chuyện.</em></h1><p class="hero-copy">Khám phá bài viết, thương hiệu, mẫu đồng hồ, bộ máy và những hiện vật được tuyển chọn từ kho NHK.</p><?php get_search_form(); ?></section>
  <section class="quick-links" aria-label="Khám phá nhanh"><a href="<?php echo esc_url(home_url('/brand/')); ?>">Thương hiệu <span>→</span></a><a href="<?php echo esc_url(home_url('/model/')); ?>">Mẫu <span>→</span></a><a href="<?php echo esc_url(home_url('/movement/')); ?>">Bộ máy <span>→</span></a><a href="<?php echo esc_url(home_url('/specimen/')); ?>">Sưu tầm <span>→</span></a></section>
  <div class="content-layout home-layout"><section class="home-feed">
    <div class="section-head"><div><p class="eyebrow">Mới nhất</p><h2>Những câu chuyện mới</h2></div><a class="text-link" href="<?php echo esc_url(get_permalink(get_option('page_for_posts')) ?: home_url('/')); ?>">Xem tất cả →</a></div>
    <?php $latest = new WP_Query(['post_type' => 'post', 'post_status' => 'publish', 'posts_per_page' => 6, 'ignore_sticky_posts' => true]); if ($latest->have_posts()): ?><div class="post-grid"><?php while ($latest->have_posts()): $latest->the_post(); get_template_part('template-parts/article-card'); endwhile; ?></div><?php else: ?><div class="empty"><p>Chưa có bài viết công khai. Nội dung sẽ xuất hiện tại đây sau khi được xuất bản.</p></div><?php endif; wp_reset_postdata(); ?>
    <?php foreach ([['Tri thức', 'tri-thuc'], ['Góc chia sẻ', 'goc-chia-se']] as $section): $category = get_category_by_slug($section[1]); if (!$category) continue; $query = new WP_Query(['post_type' => 'post', 'post_status' => 'publish', 'cat' => $category->term_id, 'posts_per_page' => 3]); if (!$query->have_posts()) { wp_reset_postdata(); continue; } ?>
      <section class="home-section"><div class="section-head"><div><p class="eyebrow"><?php echo esc_html($section[0]); ?></p><h2><?php echo esc_html($section[0]); ?> mới</h2></div><a class="text-link" href="<?php echo esc_url(get_category_link($category)); ?>">Xem thêm →</a></div><div class="post-grid compact"><?php while ($query->have_posts()): $query->the_post(); get_template_part('template-parts/article-card'); endwhile; ?></div></section>
    <?php wp_reset_postdata(); endforeach; ?>
  </section><?php get_sidebar(); ?></div>
</main><?php get_footer(); ?>
