<?php
$home = (new NHK_V3_Home_Page_Query())->read();
$GLOBALS['nhk_v3_home_data'] = $home;
get_header();
?><main id="main-content" class="site-main">
  <section class="hero"><p class="eyebrow">Kho tri thức và sưu tầm</p><h1>Mỗi chiếc đồng hồ<br> <em>mang một câu chuyện.</em></h1><p class="hero-copy">Khám phá bài viết, thương hiệu, mẫu đồng hồ, bộ máy và những hiện vật được tuyển chọn từ kho NHK.</p><?php get_search_form(); ?></section>
  <nav class="quick-links" aria-label="Khám phá nhanh"><a href="<?php echo esc_url(home_url('/brand/')); ?>">Thương hiệu <span>→</span></a><a href="<?php echo esc_url(home_url('/model/')); ?>">Mẫu <span>→</span></a><a href="<?php echo esc_url(home_url('/movement/')); ?>">Bộ máy <span>→</span></a><a href="<?php echo esc_url(home_url('/music/')); ?>">Bản nhạc <span>→</span></a><a href="<?php echo esc_url(home_url('/comparison/')); ?>">So sánh <span>→</span></a><a href="<?php echo esc_url(home_url('/component/')); ?>">Linh kiện <span>→</span></a><a href="<?php echo esc_url(home_url('/specimen/')); ?>">Hiện vật <span>→</span></a><a href="<?php echo esc_url(home_url('/video/')); ?>">Video <span>→</span></a></nav>
  <?php if (!empty($home['featured'])): $featured = $home['featured']; global $post; $post = $featured[0]; setup_postdata($post); ?>
    <section class="featured-section"><div class="section-head"><div><p class="eyebrow">Tuyển chọn</p><h2>Câu chuyện đáng đọc</h2></div></div><div class="featured-layout"><article class="featured-lead"><?php if (has_post_thumbnail()): ?><a class="featured-image" href="<?php the_permalink(); ?>"><?php the_post_thumbnail('large', ['loading' => 'eager', 'fetchpriority' => 'high']); ?></a><?php endif; ?><div class="featured-body"><p class="eyebrow"><?php $cats = get_the_category(); echo esc_html($cats[0]->name ?? 'Bài viết'); ?></p><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><p><?php echo esc_html(nhk_v3_excerpt()); ?></p><div class="meta"><span><?php echo esc_html(get_the_author()); ?></span><time datetime="<?php echo esc_attr(get_the_date('c')); ?>"><?php echo esc_html(get_the_date()); ?></time></div></div></article><div class="featured-support"><?php foreach (array_slice($featured, 1) as $post): setup_postdata($post); ?><article class="support-card"><p class="eyebrow"><?php $cats = get_the_category(); echo esc_html($cats[0]->name ?? 'Bài viết'); ?></p><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><p><?php echo esc_html(nhk_v3_excerpt()); ?></p><time datetime="<?php echo esc_attr(get_the_date('c')); ?>"><?php echo esc_html(get_the_date()); ?></time></article><?php endforeach; ?></div></div></section>
  <?php wp_reset_postdata(); endif; ?>
  <div class="content-layout home-layout"><section class="home-feed">
    <div class="section-head"><div><p class="eyebrow">Mới nhất</p><h2>Những câu chuyện mới</h2></div><a class="text-link" href="<?php echo esc_url(get_permalink(get_option('page_for_posts')) ?: home_url('/')); ?>">Xem tất cả →</a></div>
    <?php if (!empty($home['latest'])): ?><div class="post-grid"><?php foreach ($home['latest'] as $post): setup_postdata($post); get_template_part('template-parts/article-card'); endforeach; wp_reset_postdata(); ?></div><?php else: ?><div class="empty"><p>Chưa có bài viết công khai. Nội dung sẽ xuất hiện tại đây sau khi được xuất bản.</p></div><?php endif; ?>
    <?php foreach ($home['sections'] as $section): ?><section class="home-section"><div class="section-head"><div><p class="eyebrow"><?php echo esc_html($section['label']); ?></p><h2><?php echo esc_html($section['label']); ?> mới</h2></div><a class="text-link" href="<?php echo esc_url($section['url']); ?>">Xem thêm →</a></div><div class="post-grid compact"><?php foreach ($section['posts'] as $post): setup_postdata($post); get_template_part('template-parts/article-card'); endforeach; wp_reset_postdata(); ?></div></section><?php endforeach; ?>
  </section><?php get_sidebar(); ?></div>
  <?php $semantic = is_array($home['semantic'] ?? null) ? $home['semantic'] : []; if (!empty($semantic['entities'])): ?><section class="home-semantic-section"><div class="section-head"><div><p class="eyebrow">Hồ sơ nổi bật</p><h2>Khám phá sâu hơn</h2></div></div><div class="semantic-grid"><?php foreach ($semantic['entities'] as $item): ?><a class="semantic-card" href="<?php echo esc_url($item['url']); ?>"><span class="related-type"><?php echo esc_html(nhk_v3_public_type((string) $item['type'])); ?></span><strong><?php echo esc_html($item['title']); ?></strong></a><?php endforeach; ?></div></section><?php endif; ?>
  <?php if (!empty($semantic['videos'])): ?><section class="home-semantic-section"><div class="section-head"><div><p class="eyebrow">Nguồn video</p><h2>Video mới</h2></div><a class="text-link" href="<?php echo esc_url(home_url('/video/')); ?>">Xem tất cả →</a></div><div class="semantic-grid"><?php foreach ($semantic['videos'] as $item): ?><a class="semantic-card" href="<?php echo esc_url($item['url']); ?>"><span class="related-type"><?php echo esc_html($item['platform']); ?></span><strong><?php echo esc_html($item['title']); ?></strong></a><?php endforeach; ?></div></section><?php endif; ?>
  <?php if (!empty($semantic['media'])): ?><section class="home-semantic-section"><div class="section-head"><div><p class="eyebrow">Kho hình ảnh</p><h2>Media được tuyển chọn</h2></div><a class="text-link" href="<?php echo esc_url(home_url('/thu-vien/')); ?>">Mở thư viện →</a></div><div class="semantic-grid"><?php foreach ($semantic['media'] as $item): ?><a class="semantic-card" href="<?php echo esc_url($item['url']); ?>"><span class="related-type">Hình ảnh</span><strong><?php echo esc_html($item['title']); ?></strong></a><?php endforeach; ?></div></section><?php endif; ?>
  <?php if (!empty($home['topics'])): ?><section class="home-semantic-section topics-section"><div class="section-head"><div><p class="eyebrow">Được quan tâm</p><h2>Chủ đề trong kho</h2></div></div><div class="topic-cloud"><?php foreach ($home['topics'] as $topic): ?><a href="<?php echo esc_url(get_category_link($topic)); ?>"><?php echo esc_html($topic->name); ?><span><?php echo esc_html((string) $topic->count); ?></span></a><?php endforeach; ?></div></section><?php endif; ?>
</main><?php get_footer(); ?>
