<?php
get_header();
$isSearch = is_search();
$results = $isSearch ? (new NHK_V3_Search_Page_Query())->read() : null;
$editorialRoute = (string) get_query_var('nhk_editorial_route');
$archiveTitle = nhk_v3_public_editorial_label($editorialRoute) ?: nhk_v3_public_archive_title();
?><main id="main-content" class="site-main"><section class="archive-intro"><p class="eyebrow"><?php echo $isSearch ? 'Tìm kiếm' : 'Kho bài viết'; ?></p><h1><?php echo $isSearch ? sprintf('Kết quả cho: %s', esc_html($results['term'])) : esc_html($archiveTitle); ?></h1></section><div class="content-layout"><section class="feed" aria-label="Danh sách bài viết">
<?php if ($isSearch): ?>
  <?php if (!empty($results['posts'])): global $post; foreach ($results['posts'] as $post): setup_postdata($post); get_template_part('template-parts/article-card'); endforeach; wp_reset_postdata(); else: ?><div class="empty"><h2>Chưa tìm thấy bài viết</h2><p>Thử một từ khóa khác hoặc khám phá các chuyên mục của NHK.</p></div><?php endif; ?>
  <?php $labels = ['entities' => 'Hồ sơ', 'media' => 'Thư viện hình ảnh', 'videos' => 'Video', 'knowledge' => 'Tri thức']; foreach ($labels as $group => $label): if (empty($results['semantic'][$group])) continue; ?><section class="search-semantic-group"><div class="section-head"><div><p class="eyebrow">Tìm trong kho</p><h2><?php echo esc_html($label); ?></h2></div></div><div class="semantic-grid"><?php foreach ($results['semantic'][$group] as $item): $url = nhk_v3_public_url($item['url'] ?? null); if ($url === '') continue; ?><a class="semantic-card" href="<?php echo esc_url($url); ?>"><span class="related-type"><?php echo esc_html(nhk_v3_public_type((string) ($item['type'] ?? $group))); ?></span><strong><?php echo esc_html(nhk_v3_public_brand_text((string) ($item['title'] ?? ''))); ?></strong></a><?php endforeach; ?></div></section><?php endforeach; ?>
  <?php $semanticTotals = is_array($results['semantic']['_totals'] ?? null) ? $results['semantic']['_totals'] : []; $semanticMax = $semanticTotals === [] ? 0 : max(array_map('intval', $semanticTotals)); $pages = max((int) ceil($results['total'] / 12), (int) ceil($semanticMax / 12)); if ($pages > 1): ?><nav class="entity-pagination" aria-label="Phân trang tìm kiếm"><?php for ($page = 1; $page <= $pages; $page++): $url = add_query_arg(['s' => $results['term'], 'paged' => $page], home_url('/')); $current = $page === max(1, (int) get_query_var('paged', 1)); ?><a class="<?php echo $current ? 'current' : ''; ?>"<?php echo $current ? ' aria-current="page"' : ''; ?> href="<?php echo esc_url($url); ?>"><?php echo esc_html((string) $page); ?></a><?php endfor; ?></nav><?php endif; ?>
<?php elseif (have_posts()): while (have_posts()): the_post(); get_template_part('template-parts/article-card'); endwhile; the_posts_pagination(['mid_size' => 1, 'prev_text' => '← Mới hơn', 'next_text' => 'Cũ hơn →']); else: ?><div class="empty"><h2>Chưa tìm thấy nội dung</h2><p>Thử một từ khóa khác hoặc khám phá các chuyên mục của NHK.</p></div><?php endif; ?>
</section><?php get_sidebar(); ?></div></main><?php get_footer(); ?>
