<?php
/* public seo_projection supplies canonical link results; posts keep native permalinks. */
get_header();
$isSearch = is_search();
$results = $isSearch ? (new NHK_V3_Search_Page_Query())->read() : null;
$editorialRoute = (string) get_query_var('nhk_editorial_route');
$archiveTitle = nhk_v3_public_editorial_label($editorialRoute) ?: nhk_v3_public_archive_title();
?><main id="main-content" class="site-main"><section class="archive-intro"><p class="eyebrow"><?php echo $isSearch ? 'Tìm kiếm' : 'Kho bài viết'; ?></p><h1><?php echo $isSearch ? ($results['term'] !== '' ? sprintf('Kết quả tìm kiếm “%s”', esc_html($results['term'])) : 'Tìm trong NHK') : esc_html($archiveTitle); ?></h1></section><div class="content-layout"><section class="feed" aria-label="Danh sách bài viết">
<?php if ($isSearch): ?>
  <?php $semantic = is_array($results['semantic'] ?? null) ? $results['semantic'] : []; $hasPosts = !empty($results['posts']); $hasEntities = !empty($semantic['entities']); $hasMedia = !empty($semantic['media']); $hasVideos = !empty($semantic['videos']); $hasKnowledge = !empty($semantic['knowledge']); $hasAnyResults = $hasPosts || $hasEntities || $hasMedia || $hasVideos || $hasKnowledge; ?>
  <?php if ($results['term'] === ''): ?><?php get_template_part('template-parts/presentation/empty-state', null, ['class' => 'empty search-empty', 'title' => 'Tìm trong NHK', 'message' => 'Nhập tên thương hiệu, loại đồng hồ, bộ máy hoặc thuật ngữ để bắt đầu.']); ?><?php get_search_form(); ?>
  <?php elseif (!$hasAnyResults): ?><?php get_template_part('template-parts/presentation/empty-state', null, ['class' => 'empty search-empty', 'title' => 'Chưa tìm thấy kết quả phù hợp', 'message' => 'Thử tên thương hiệu, loại đồng hồ, bộ máy hoặc thuật ngữ khác.']); ?>
  <?php else: ?><p class="search-results-summary">Tìm thấy nội dung trong <?php echo esc_html((string) count(array_filter([$hasPosts, $hasEntities, $hasMedia, $hasVideos, $hasKnowledge]))); ?> nhóm.</p>
    <?php if ($hasPosts): ?><section class="search-result-group"><div class="section-head"><div><p class="eyebrow">Tìm trong kho</p><h2>Bài viết</h2></div></div><div class="post-grid"><?php global $post; foreach ($results['posts'] as $post): setup_postdata($post); get_template_part('template-parts/article-card'); endforeach; wp_reset_postdata(); ?></div></section><?php endif; ?>
    <?php $labels = ['entities' => 'Hồ sơ', 'media' => 'Hình ảnh', 'videos' => 'Video', 'knowledge' => 'Tri thức']; foreach ($labels as $group => $label): if (empty($semantic[$group])) continue; ?><section class="search-result-group"><div class="section-head"><div><p class="eyebrow">Tìm trong kho</p><h2><?php echo esc_html($label); ?></h2></div></div><div class="semantic-grid"><?php foreach ($semantic[$group] as $item): $url = nhk_v3_public_url($item['url'] ?? null); if ($url === '') continue; $itemProfile = (string) ($item['profile_key'] ?? ''); $itemBadge = trim((string) ($item['profile_badge'] ?? '')); $displayType = nhk_v3_public_type((string) ($item['type'] ?? $group)); if ($itemProfile !== '') $displayType = nhk_v3_public_type((string) ($item['type'] ?? $group), $itemProfile); if ($group === 'entities') { get_template_part('template-parts/presentation/entity-card', null, ['item' => $item, 'label' => $itemBadge !== '' ? $itemBadge : $displayType]); continue; } ?><a class="semantic-card" href="<?php echo esc_url($url); ?>"><span class="related-type"><?php echo esc_html($itemBadge !== '' ? $itemBadge : $displayType); ?></span><strong><?php echo esc_html(nhk_v3_public_brand_text((string) ($item['title'] ?? ''))); ?></strong></a><?php endforeach; ?></div></section><?php endforeach; ?>
  <?php endif; ?>
  <?php $semanticTotals = is_array($results['semantic']['_totals'] ?? null) ? $results['semantic']['_totals'] : []; $semanticMax = $semanticTotals === [] ? 0 : max(array_map('intval', $semanticTotals)); $pages = max((int) ceil($results['total'] / 12), (int) ceil($semanticMax / 12)); if ($pages > 1): ?><nav class="entity-pagination" aria-label="Phân trang tìm kiếm"><?php for ($page = 1; $page <= $pages; $page++): $url = add_query_arg(['s' => $results['term'], 'paged' => $page], home_url('/')); $current = $page === max(1, (int) get_query_var('paged', 1)); ?><a class="<?php echo $current ? 'current' : ''; ?>"<?php echo $current ? ' aria-current="page"' : ''; ?> href="<?php echo esc_url($url); ?>"><?php echo esc_html((string) $page); ?></a><?php endfor; ?></nav><?php endif; ?>
<?php elseif (have_posts()): ?><div class="post-grid"><?php while (have_posts()): the_post(); get_template_part('template-parts/article-card'); endwhile; ?></div><?php the_posts_pagination(['mid_size' => 1, 'prev_text' => '← Mới hơn', 'next_text' => 'Cũ hơn →']); else: ?><?php get_template_part('template-parts/presentation/empty-state', null, ['title' => 'Chưa tìm thấy nội dung', 'message' => 'Thử một từ khóa khác hoặc khám phá các chuyên mục của NHK.']); ?><?php endif; ?>
</section><?php get_sidebar(); ?></div></main><?php get_footer(); ?>
