<?php
$context = $GLOBALS['nhk_core_knowledge_context'] ?? null;
$archiveUrl = is_array($context) ? (string) ($context['archive_url'] ?? home_url('/tri-thuc/')) : home_url('/tri-thuc/');
get_header();
?><main id="main-content" class="site-main knowledge-shell">
<?php if (is_array($context) && ($context['mode'] ?? '') === 'detail' && is_array($context['claim'] ?? null)): $claim = $context['claim']; ?>
  <p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">NHK</a> <span>/</span> <a href="<?php echo esc_url($archiveUrl); ?>">Tri thức</a></p>
  <article class="knowledge-article"><header class="article-header"><p class="eyebrow">Tri thức · <?php echo esc_html(nhk_v3_public_type((string) $claim['type'])); ?></p><h1><?php echo esc_html(nhk_v3_public_brand_text((string) $claim['text'])); ?></h1></header><div class="knowledge-definition"><p><?php echo esc_html(nhk_v3_public_brand_text((string) $claim['text'])); ?></p></div><?php if (!empty($claim['evidence'])): ?><section class="knowledge-evidence"><h2>Nguồn và bằng chứng</h2><?php foreach ($claim['evidence'] as $item): $locator = nhk_v3_public_url($item['locator'] ?? ($item['source_locator'] ?? null)); ?><article><?php if (!empty($item['source_title'])): ?><p class="eyebrow"><?php echo esc_html(nhk_v3_public_brand_text((string) $item['source_title'])); ?><?php if (!empty($item['source_type'])): ?> · <?php echo esc_html(nhk_v3_public_type((string) $item['source_type'])); ?><?php endif; ?></p><?php endif; ?><p><?php echo esc_html(nhk_v3_public_brand_text((string) $item['excerpt'])); ?></p><?php if ($locator !== ''): ?><a href="<?php echo esc_url($locator); ?>" rel="nofollow noopener">Mở nguồn</a><?php endif; ?></article><?php endforeach; ?></section><?php else: ?><p class="knowledge-note">Bằng chứng công khai chưa được phát hành; nội dung chỉ hiển thị tri thức đã được kiểm soát.</p><?php endif; ?></article>
<?php elseif (is_array($context) && is_array($context['archive'] ?? null)): $archive = $context['archive']; ?>
  <header class="archive-intro"><p class="eyebrow">Tri thức</p><h1>Kho tri thức</h1><p class="archive-summary">Các thông tin đã được kiểm chứng đang hoạt động trong kho NHK.</p></header><div class="knowledge-grid"><?php if (!empty($archive['items'])): foreach ($archive['items'] as $item): $itemUrl = nhk_v3_public_url($item['url'] ?? null); if ($itemUrl === '') continue; ?><article class="knowledge-card"><p class="eyebrow"><?php echo esc_html(nhk_v3_public_type((string) $item['type'])); ?></p><h2><a href="<?php echo esc_url($itemUrl); ?>"><?php echo esc_html(nhk_v3_public_brand_text((string) $item['text'])); ?></a></h2></article><?php endforeach; else: ?><div class="empty"><h2>Chưa có thông tin</h2><p>Kho tri thức hiện chưa có dữ liệu công khai.</p></div><?php endif; ?></div><?php $pages = (int) ceil((int) ($archive['total'] ?? 0) / max(1, (int) ($archive['per_page'] ?? 1))); if ($pages > 1): ?><nav class="entity-pagination" aria-label="Phân trang tri thức"><?php for ($page = 1; $page <= $pages; $page++): $url = home_url('/knowledge/' . ($page > 1 ? 'page/' . $page . '/' : '')); $current = $page === (int) ($archive['page'] ?? 1); ?><a class="<?php echo $current ? 'current' : ''; ?>"<?php echo $current ? ' aria-current="page"' : ''; ?> href="<?php echo esc_url($url); ?>"><?php echo esc_html((string) $page); ?></a><?php endfor; ?></nav><?php endif; ?>
<?php endif; ?></main><?php get_footer();
