<?php
$context = $GLOBALS['nhk_core_video_context'] ?? null;
$archive = is_array($context) ? ($context['archive'] ?? []) : [];
$video = is_array($context) ? ($context['video'] ?? []) : [];
get_header();
?><main id="main-content" class="site-main media-video-shell">
<?php if (is_array($context) && ($context['mode'] ?? '') === 'detail' && $video !== []): $platform = strtolower((string) ($video['platform'] ?? '')); $externalId = (string) ($video['external_id'] ?? ''); ?>
  <p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">NHK</a> <span>/</span> <a href="<?php echo esc_url(home_url('/video/')); ?>">Video</a></p>
  <header class="archive-intro media-header"><p class="eyebrow"><?php echo esc_html($platform ?: 'Nguồn video'); ?></p><h1><?php echo esc_html((string) ($video['title'] ?: 'Video NHK')); ?></h1><p class="archive-summary">Video được tham chiếu từ nguồn bên ngoài; NHK không sao chép hoặc lưu MP4 local.</p></header>
  <?php if ($platform === 'youtube' && preg_match('/^[A-Za-z0-9_-]{11}$/', $externalId)): ?><div class="video-frame"><iframe src="https://www.youtube-nocookie.com/embed/<?php echo esc_attr($externalId); ?>" title="<?php echo esc_attr((string) ($video['title'] ?: 'Video NHK')); ?>" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><?php endif; ?>
  <div class="video-facts"><dl class="entity-facts"><dt>Nền tảng</dt><dd><?php echo esc_html($platform); ?></dd><?php $sourceUrl = nhk_v3_public_url($video['url'] ?? null); if ($sourceUrl !== ''): ?><dt>Địa chỉ nguồn</dt><dd><a class="text-link" href="<?php echo esc_url($sourceUrl); ?>" rel="noopener noreferrer">Mở nguồn video ↗</a></dd><?php endif; ?></dl></div>
<?php elseif (is_array($context) && is_array($archive)): ?>
  <header class="archive-intro"><p class="eyebrow">Nguồn video</p><h1>Video</h1><p class="archive-summary">Các video tham chiếu được kiểm soát và liên kết từ nguồn bên ngoài.</p></header>
  <?php if (!empty($archive['items'])): ?><div class="media-card-grid"><?php foreach ($archive['items'] as $item): $itemUrl = nhk_v3_public_url($item['public_url'] ?? null); $sourceUrl = nhk_v3_public_url($item['source_url'] ?? null); if ($itemUrl === '') continue; ?><article class="media-card"><p class="eyebrow"><?php echo esc_html((string) ($item['platform'] ?? 'Video')); ?></p><h2><a href="<?php echo esc_url($itemUrl); ?>"><?php echo esc_html((string) ($item['title'] ?: 'Video NHK')); ?></a></h2><?php if ($sourceUrl !== ''): ?><p><a class="text-link" href="<?php echo esc_url($sourceUrl); ?>" rel="noopener noreferrer">Mở nguồn ↗</a></p><?php endif; ?></article><?php endforeach; ?></div><?php else: ?><div class="empty media-empty"><h2>Chưa có video công khai</h2><p>Video chỉ xuất hiện sau khi nguồn hợp lệ và được kiểm duyệt.</p></div><?php endif; ?>
  <?php $pages = (int) ceil((int) ($archive['total'] ?? 0) / max(1, (int) ($archive['per_page'] ?? 1))); if ($pages > 1): ?><nav class="entity-pagination" aria-label="Phân trang video"><?php for ($page = 1; $page <= $pages; $page++): $url = home_url('/video/' . ($page > 1 ? 'page/' . $page . '/' : '')); $current = $page === (int) ($archive['page'] ?? 1); ?><a class="<?php echo $current ? 'current' : ''; ?>"<?php echo $current ? ' aria-current="page"' : ''; ?> href="<?php echo esc_url($url); ?>"><?php echo esc_html((string) $page); ?></a><?php endfor; ?></nav><?php endif; ?>
<?php else: ?><div class="empty"><h1>Video chưa sẵn sàng</h1><p>Không thể tải dữ liệu video.</p></div><?php endif; ?></main><?php get_footer();
