<?php
/* public seo_projection supplies canonical link results. */
$context = $GLOBALS['nhk_core_video_context'] ?? null;
$archive = is_array($context) ? ($context['archive'] ?? []) : [];
$video = is_array($context) ? ($context['video'] ?? []) : [];
get_header();
?><main id="main-content" class="site-main media-video-shell">
<?php if (is_array($context) && ($context['mode'] ?? '') === 'detail' && $video !== []): $platform = strtolower((string) ($video['platform'] ?? '')); $externalId = (string) ($video['external_id'] ?? ''); $title = (string) (($video['title'] ?? '') ?: 'Video NHK'); ?>
  <p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">NHK</a> <span>/</span> <a href="<?php echo esc_url(home_url('/video/')); ?>">Video</a></p>
  <header class="archive-intro media-header"><p class="eyebrow"><?php echo esc_html($platform ?: 'Nguồn video'); ?></p><h1><?php echo esc_html(nhk_v3_public_brand_text($title)); ?></h1><?php if (($video['summary'] ?? '') !== ''): ?><p class="archive-summary"><?php echo esc_html(nhk_v3_public_brand_text((string) $video['summary'])); ?></p><?php endif; ?></header>
  <?php if (($video['source_available'] ?? true) && $platform === 'youtube' && preg_match('/^[A-Za-z0-9_-]{11}$/', $externalId)): ?><div class="video-frame"><iframe src="<?php echo esc_url((string) ($video['embed_url'] ?? 'https://www.youtube-nocookie.com/embed/' . $externalId)); ?>" title="<?php echo esc_attr(nhk_v3_public_brand_text($title)); ?>" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><?php elseif (($video['source_available'] ?? true) === false): ?><div class="empty media-empty"><h2>Video nguồn hiện không khả dụng</h2><p>Hồ sơ NHK vẫn được giữ lại; phần phát video sẽ trở lại khi nguồn bên ngoài sẵn sàng.</p></div><?php endif; ?>
  <?php if (($video['body'] ?? '') !== '' || ($video['why_this_matters'] ?? '') !== ''): ?><article class="video-editorial"><h2>Về video này</h2><?php if (($video['body'] ?? '') !== ''): ?><p><?php echo esc_html(nhk_v3_public_brand_text((string) $video['body'])); ?></p><?php endif; ?><?php if (($video['why_this_matters'] ?? '') !== ''): ?><p><?php echo esc_html(nhk_v3_public_brand_text((string) $video['why_this_matters'])); ?></p><?php endif; ?></article><?php endif; ?>
  <div class="video-facts"><dl class="entity-facts"><dt>Nền tảng</dt><dd><?php echo esc_html($platform); ?></dd><?php if (is_array($video['category'] ?? null)): ?><dt>Chủ đề</dt><dd><?php echo esc_html((string) ($video['category']['label'] ?? '')); ?></dd><?php endif; ?><?php $sourceUrl = nhk_v3_public_url($video['url'] ?? null); if ($sourceUrl !== ''): ?><dt>Địa chỉ nguồn</dt><dd><a class="text-link" href="<?php echo esc_url($sourceUrl); ?>" rel="noopener noreferrer">Mở nguồn video ↗</a></dd><?php endif; ?></dl></div>
  <?php if (is_array($video['related'] ?? null)): foreach (['entities' => 'Liên quan', 'articles' => 'Bài viết liên quan', 'media' => 'Hình ảnh liên quan', 'videos' => 'Video liên quan'] as $group => $label): if (!empty($video['related'][$group])): ?><section class="video-related"><h2><?php echo esc_html($label); ?></h2><ul><?php foreach ($video['related'][$group] as $item): $relatedUrl = nhk_v3_public_url($item['url'] ?? null); if ($relatedUrl === '') continue; ?><li><a href="<?php echo esc_url($relatedUrl); ?>"><?php echo esc_html(nhk_v3_public_brand_text((string) ($item['title'] ?? ''))); ?></a></li><?php endforeach; ?></ul></section><?php endif; endforeach; endif; ?>
<?php elseif (is_array($context) && is_array($archive)): ?>
  <header class="archive-intro"><p class="eyebrow">Nguồn video</p><h1>Video</h1><p class="archive-summary">Các video tham chiếu được kiểm soát và liên kết từ nguồn bên ngoài.</p></header>
  <?php if (!empty($archive['items'])): ?><div class="media-card-grid"><?php foreach ($archive['items'] as $item): $itemUrl = nhk_v3_public_url($item['public_url'] ?? null); $sourceUrl = nhk_v3_public_url($item['source_url'] ?? null); if ($itemUrl === '') continue; ?><article class="media-card"><p class="eyebrow"><?php echo esc_html((string) ($item['platform'] ?? 'Video')); ?></p><h2><a href="<?php echo esc_url($itemUrl); ?>"><?php echo esc_html(nhk_v3_public_brand_text((string) ($item['title'] ?: 'Video NHK'))); ?></a></h2><?php if ($sourceUrl !== ''): ?><p><a class="text-link" href="<?php echo esc_url($sourceUrl); ?>" rel="noopener noreferrer">Mở nguồn ↗</a></p><?php endif; ?></article><?php endforeach; ?></div><?php else: ?><div class="empty media-empty"><h2>Chưa có video công khai</h2><p>Video chỉ xuất hiện sau khi nguồn hợp lệ và được kiểm duyệt.</p></div><?php endif; ?>
  <?php $pages = (int) ceil((int) ($archive['total'] ?? 0) / max(1, (int) ($archive['per_page'] ?? 1))); if ($pages > 1): ?><nav class="entity-pagination" aria-label="Phân trang video"><?php for ($page = 1; $page <= $pages; $page++): $url = home_url('/video/' . ($page > 1 ? 'page/' . $page . '/' : '')); $current = $page === (int) ($archive['page'] ?? 1); ?><a class="<?php echo $current ? 'current' : ''; ?>"<?php echo $current ? ' aria-current="page"' : ''; ?> href="<?php echo esc_url($url); ?>"><?php echo esc_html((string) $page); ?></a><?php endfor; ?></nav><?php endif; ?>
<?php else: ?><div class="empty"><h1>Video chưa sẵn sàng</h1><p>Không thể tải dữ liệu video.</p></div><?php endif; ?></main><?php get_footer();
